ccflags-y :=                            \
        -Idrivers/unisoc_platform/sprdwcn/include \
        -Idrivers/unisoc_platform/sprdwcn/platform \
        -Idrivers/unisoc_platform/sprdwcn/platform/rf
obj-$(CONFIG_WCN_INTEG) +=  wcn_integrate_dev.o \
	wcn_integrate_boot.o wcn_integrate.o
