# include header files for MTK
obj-$(CONFIG_TOUCHSCREEN_ILI9882N_SKY)	+=  ilitek_v3.o
obj-$(CONFIG_TOUCHSCREEN_ILI9882N_SKY)	+=	ilitek_v3_i2c.o 
obj-$(CONFIG_TOUCHSCREEN_ILI9882N_SKY)  +=	ilitek_v3_qcom.o 
obj-$(CONFIG_TOUCHSCREEN_ILI9882N_SKY)	+=	ilitek_v3_ic.o
obj-$(CONFIG_TOUCHSCREEN_ILI9882N_SKY)	+=	ilitek_v3_touch.o 
obj-$(CONFIG_TOUCHSCREEN_ILI9882N_SKY)	+=	ilitek_v3_mp.o
obj-$(CONFIG_TOUCHSCREEN_ILI9882N_SKY)	+=	ilitek_v3_flash.o 
obj-$(CONFIG_TOUCHSCREEN_ILI9882N_SKY)	+=	ilitek_v3_node.o

