obj-$(CONFIG_SPRD_7SRESET)	+= sprd_7sreset.o
obj-$(CONFIG_SPRD_DEBUG)	+= debug/
obj-$(CONFIG_SPRD_SYSDUMP)      += debug/sysdump/
obj-y				+= autotest/
obj-y				+= domain/
obj-$(CONFIG_SPRD_IOMMU)        += iommu/
obj-$(CONFIG_SPRD_MEMDISK)	+= sprd_memdisk.o
