#
# Makefile for the sprd staging modem files
#
obj-$(CONFIG_SPRD_SIPC)		+= sipc/
obj-$(CONFIG_SPRD_CPROC)	+= cproc/
obj-$(CONFIG_SPRD_IQ)		+= iq/
obj-$(CONFIG_SPRD_HW_DEVICE_DVFS_CP)	+= dvfs/
obj-$(CONFIG_SPRD_MCD)  += mcd/
