# MCDT(Multi-channel Data Transfer) Support
SPRD_AUDIO_ASSISTANT_TREE := drivers/unisoc_platform/audio/sprd_audio
ccflags-y	+= -I$(srctree)/$(SPRD_AUDIO_ASSISTANT_TREE)/mcdt/

obj-$(CONFIG_UNISOC_AUDIO_MCDT_R2P0)	+= mcdt_hw_r2p0.o
