
obj-y += lcd_flash_drv.o
ccflags-y += -I$(srctree)/drivers/misc/sprd_camera/flash \
            -I$(srctree)/drivers/video/adf/sprd/drv \
            -I$(srctree)/drivers/video/adf/sprd/core/include \
            -I$(srctree)/drivers/staging/android/ion
