# SPDX-License-Identifier: GPL-2.0
obj-$(CONFIG_UNISOC_DISP)	+= sprd_disp/
obj-$(CONFIG_SPRD_DEBUG)	+= debug/
obj-$(CONFIG_SPRD_SYSDUMP) 	+= sysdump/
obj-$(CONFIG_UNISOC_IOMMU)	+= iommu/
obj-$(CONFIG_UNISOC_MODEM)	+= modem/
obj-$(CONFIG_PRINTK_CPUID)	+= printk_cpuid/
