# SPDX-License-Identifier: GPL-2.0
obj-$(CONFIG_UNISOC_IOMMU)			+= iommu/
obj-$(CONFIG_UNISOC_MODEM_LOADER)		+= modem_loader/
obj-$(CONFIG_UNISOC_SIPC_VIRT_BUS)		+= sipc_virt_bus/
obj-$(CONFIG_UNISOC_MAILBOX)			+= mailbox/
obj-$(CONFIG_UNISOC_WCN_BSP)			+= sprdwcn/
obj-$(CONFIG_UNISOC_GNSS)                       += sprd_gnss/
obj-$(CONFIG_SND_SOC)				+= audio/
