# SPDX-License-Identifier: GPL-2.0

# NOTE: Keep order __alphabetically__ PLEASE!! #

obj-$(CONFIG_ARCH_SPRD)		+= pub/
obj-$(CONFIG_CPU_FREQ) 		+= cpufreq/
obj-$(CONFIG_IRQSOFF_WARN)	+= preemptirq_warn/
obj-$(CONFIG_IRQ_MONITOR)	+= irq_monitor/
obj-$(CONFIG_PREEMPT_WARN) 	+= preemptirq_warn/
obj-$(CONFIG_PRINTK_CPUID)	+= printk_cpuid/
obj-$(CONFIG_SND_SOC)		+= audio/
obj-$(CONFIG_SPRD_DEBUG)	+= debug/
obj-$(CONFIG_SPRD_MODEM_DEBUG)	+= debug_log/
obj-$(CONFIG_SPRD_PMIC_SMPL)	+= sprd_pmic_smpl.o
obj-$(CONFIG_SPRD_PMIC_SYSCON)  += sprd_pmic_syscon.o
obj-$(CONFIG_SPRD_SFP_SUPPORT)	+= sfp/
obj-$(CONFIG_SPRD_SYSDUMP) 	+= sysdump/
obj-$(CONFIG_TIMESTAMP_SYNC)	+= kts_sync/
obj-$(CONFIG_UNISOC_7SRESET)	+= sprd_7sreset.o
obj-$(CONFIG_UNISOC_DISP)	+= sprd_disp/
obj-$(CONFIG_UNISOC_DMABUF)	+= dmabufheap/
obj-$(CONFIG_UNISOC_GNSS)	+= sprd_gnss/
obj-$(CONFIG_UNISOC_IOMMU)	+= iommu/
obj-$(CONFIG_UNISOC_MODEM)	+= modem/
obj-$(CONFIG_UNISOC_SCHED)	+= sched/
obj-$(CONFIG_UNISOC_WCN_BSP)	+= sprdwcn/
obj-$(CONFIG_WLAN_VENDOR_SPREADTRUM)		+= wlan/
obj-$(CONFIG_SPRD_HANG_DEBUG) 	+= hang_debug/
obj-$(CONFIG_UNISOC_USERLOG)    += userlog/
obj-$(CONFIG_UNISOC_CORESIGHT)    += sprd_coresight/
obj-y += net/
obj-y += sprd_time_sync/
obj-y += power/
obj-y += thermal/
obj-y += performance/
