# SPDX-License-Identifier: GPL-2.0-only

subdir-ccflags-y += -I$(srctree)/$(src)
#subdir-ccflags-y += -DDRV_RESET_SELF

obj-$(CONFIG_SPRD_WLAN)		+= common/

obj-$(CONFIG_SC2332_WLAN)	+= sc2332/

obj-$(CONFIG_SC2355_WLAN)	+= sc2355/

obj-$(CONFIG_SC2355_SIPC_WLAN)	+= marlin3_sipc/
