SPRD_AUDIO_ASSISTANT_TREE := drivers/unisoc_platform/audio/sprd_audio
ccflags-y += -I$(srctree)/$(SPRD_AUDIO_ASSISTANT_TREE)/audiomem/ \
		-I$(srctree)/$(SPRD_AUDIO_ASSISTANT_TREE)/audiosipc/ \
		-I$(srctree)/$(SPRD_AUDIO_ASSISTANT_TREE)/include

obj-$(CONFIG_UNISOC_AUDIO_CPBOOT)		+= sprd_audcp_boot.o
