# include header files for MTK
obj-$(CONFIG_TOUCHSCREEN_ILI9882H_SKY_SPI)	+=  ilitek_v3.o
obj-$(CONFIG_TOUCHSCREEN_ILI9882H_SKY_SPI)	+=	ilitek_v3_spi.o
obj-$(CONFIG_TOUCHSCREEN_ILI9882H_SKY_SPI)  	+=	ilitek_v3_qcom.o
obj-$(CONFIG_TOUCHSCREEN_ILI9882H_SKY_SPI)	+=	ilitek_v3_ic.o
obj-$(CONFIG_TOUCHSCREEN_ILI9882H_SKY_SPI)	+=	ilitek_v3_touch.o
obj-$(CONFIG_TOUCHSCREEN_ILI9882H_SKY_SPI)	+=	ilitek_v3_mp.o
obj-$(CONFIG_TOUCHSCREEN_ILI9882H_SKY_SPI)	+=	ilitek_v3_hostdl.o
obj-$(CONFIG_TOUCHSCREEN_ILI9882H_SKY_SPI)	+=	ilitek_v3_node.o

