# SPRD audio assistant modules

obj-$(CONFIG_UNISOC_AUDIO_AGDSP_ACCESS)		+= agdsp_access/
obj-$(CONFIG_UNISOC_AUDIO_DSP_DUMP)		+= audiodspdump/
obj-$(CONFIG_UNISOC_AUDIO_MEMORY_MANAGER)		+= audiomem/
obj-$(CONFIG_UNISOC_AUDIO_PIPE)		+= audio_pipe/
obj-$(CONFIG_UNISOC_AUDIO_SIPC)			+= audiosipc/
obj-$(CONFIG_UNISOC_AUDIO_MCDT)			+= mcdt/
obj-$(CONFIG_UNISOC_HW_DEVICE_DVFS_AGCP) 		+= audiodvfs/
obj-$(CONFIG_UNISOC_AUDIO_CPBOOT)			+= audiocpboot/
obj-$(CONFIG_UNISOC_AUDIO_SAUDIO)			+= saudio/
