subdir-ccflags-y := \
	-I$(src)/include \
	-I$(src)/boot \
	-I$(src)/platform \
	-I$(src)/platform/rf
obj-$(CONFIG_SC23XX) += wcn_bus.o
obj-$(CONFIG_SDIOHAL) += sdio/
obj-$(CONFIG_WCN_SLP) += sleep/
obj-$(CONFIG_WCN_BOOT) += platform/
