obj-$(CONFIG_TYPEC)		+= typec.o
typec-y				:= class.o mux.o
obj-$(CONFIG_TYPEC_TCPM)	+= tcpm.o
obj-$(CONFIG_TYPEC_WCOVE)	+= typec_wcove.o
obj-$(CONFIG_TYPEC_UCSI)	+= ucsi/
obj-$(CONFIG_USB_SC27XX_TYPEC)	+= sc27xx_typec.o
