HAVE_KERNEL_5_15 = $(shell test -d $(ANDROID_BUILD_TOP)/bsp/kernel5.15/kernel5.15 && echo 1)

ZRAM_SRC = zram-5.15
EXTRA_CFLAGS += -DCONFIG_ZRAM_5_15

# add -Wall to try to catch everything we can.
EXTRA_CFLAGS += -Wall
EXTRA_CFLAGS += -I$(ANDROID_BUILD_TOP)/bsp/kernel5.15/kernel5.15/include
EXTRA_CFLAGS += -I$(ANDROID_BUILD_TOP)/bsp/kernel5.15/kernel5.15/ramboot/moto_swap/hybridswap

#ifneq ($(filter m y,$(CONFIG_HYBRIDSWAP_ZRAM)),)
EXTRA_CFLAGS += -DCONFIG_HYBRIDSWAP_ZRAM
#endif

#ifneq ($(filter m y,$(CONFIG_HYBRIDSWAP_ZRAM_WRITEBACK)),)
#EXTRA_CFLAGS += -DCONFIG_HYBRIDSWAP_ZRAM_WRITEBACK
#endif

#ifneq ($(filter m y,$(CONFIG_HYBRIDSWAP)),)
EXTRA_CFLAGS += -DCONFIG_HYBRIDSWAP
#endif

#ifneq ($(filter m y,$(CONFIG_HYBRIDSWAP_SWAPD)),)
EXTRA_CFLAGS += -DCONFIG_HYBRIDSWAP_SWAPD
#endif

#ifneq ($(filter m y,$(CONFIG_HYBRIDSWAP_CORE)),)
EXTRA_CFLAGS += -DCONFIG_HYBRIDSWAP_CORE
#endif

moto_swap-objs += $(ZRAM_SRC)/zram_drv.o
moto_swap-objs += hybridswap/hybridswap_main.o
moto_swap-objs += hybridswap/hybridswap_eswap.o

ifneq ($(filter m y,$(CONFIG_HYBRIDSWAP_ASYNC_COMPRESS)),)
moto_swap-objs += hybridswap/hybridswap_akcompress.o
endif

moto_swap-objs += hybridswap/hybridswap_swapd.o
moto_swap-objs += $(ZRAM_SRC)/zcomp.o

obj-m += moto_swap.o
