#
# Makefile for all kinds of Fingerprint
#

#obj-$(CONFIG_FPS_FPC_S00)  += fps_fpc_S00/
#obj-$(CONFIG_FPS_GOODIX_S00)  += fps_goodix_S00/
obj-$(CONFIG_FPS_FPSENSOR_S00)  += fps_fpsensor_S00/
obj-$(CONFIG_FPS_EGIS_S00)  += fps_egis_S00/
