# controllers
obj-$(CONFIG_TOUCHSCREEN_ADAPTIVE) += adaptive-ts.o
adaptive-ts-objs := ats_core.o
adaptive-ts-objs += ats_loader.o
adaptive-ts-objs += ats_event.o
adaptive-ts-objs += ats_i2c.o
adaptive-ts-objs += ats_spi.o
adaptive-ts-objs += vendors/dummy/ats_dummy.o
adaptive-ts-${CONFIG_TOUCHSCREEN_ADAPTIVE_TLSC6X}-objs += vendors/tlsc6x/ats_tlsc6x.o
adaptive-ts-${CONFIG_TOUCHSCREEN_ADAPTIVE_TLSC6X}-objs += vendors/tlsc6x/ats_tlsc6x_comp.o
adaptive-ts-${CONFIG_TOUCHSCREEN_ADAPTIVE_NT36XXX}-objs += vendors/nt36xxx/ats_nt36xxx_ext_proc.o
adaptive-ts-${CONFIG_TOUCHSCREEN_ADAPTIVE_NT36XXX}-objs += vendors/nt36xxx/ats_nt36xxx_fw_update.o
adaptive-ts-${CONFIG_TOUCHSCREEN_ADAPTIVE_NT36XXX}-objs += vendors/nt36xxx/ats_nt36xxx_mp_ctrlram.o
adaptive-ts-${CONFIG_TOUCHSCREEN_ADAPTIVE_NT36XXX}-objs += vendors/nt36xxx/ats_nt36xxx.o
adaptive-ts-${CONFIG_TOUCHSCREEN_ADAPTIVE_NT36XXX_SPI}-objs += vendors/nt36xxx_spi/ats_nt36xxx_ext_proc.o
adaptive-ts-${CONFIG_TOUCHSCREEN_ADAPTIVE_NT36XXX_SPI}-objs += vendors/nt36xxx_spi/ats_nt36xxx_fw_update.o
adaptive-ts-${CONFIG_TOUCHSCREEN_ADAPTIVE_NT36XXX_SPI}-objs += vendors/nt36xxx_spi/ats_nt36xxx_mp_ctrlram.o
adaptive-ts-${CONFIG_TOUCHSCREEN_ADAPTIVE_NT36XXX_SPI}-objs += vendors/nt36xxx_spi/ats_nt36xxx_spi.o
adaptive-ts-${CONFIG_TOUCHSCREEN_ADAPTIVE_ILI9882H}-objs += vendors/ili9882h/ats_ili9882h.o
adaptive-ts-${CONFIG_TOUCHSCREEN_ADAPTIVE_ILI9882H}-objs += vendors/ili9882h/ats_ili9882.o
adaptive-ts-${CONFIG_TOUCHSCREEN_ADAPTIVE_ILI9882H}-objs += vendors/ili9882h/ats_ili9882_flash.o
adaptive-ts-${CONFIG_TOUCHSCREEN_ADAPTIVE_ILI9882H}-objs += vendors/ili9882h/ats_ili9882_i2c.o
adaptive-ts-${CONFIG_TOUCHSCREEN_ADAPTIVE_ILI9882H}-objs += vendors/ili9882h/ats_ili9882_ic.o
adaptive-ts-${CONFIG_TOUCHSCREEN_ADAPTIVE_ILI9882H}-objs += vendors/ili9882h/ats_ili9882_mp.o
adaptive-ts-${CONFIG_TOUCHSCREEN_ADAPTIVE_ILI9882H}-objs += vendors/ili9882h/ats_ili9882_node.o
adaptive-ts-${CONFIG_TOUCHSCREEN_ADAPTIVE_ILI9882H}-objs += vendors/ili9882h/ats_ili9882_qcom.o
adaptive-ts-${CONFIG_TOUCHSCREEN_ADAPTIVE_ILI9882H}-objs += vendors/ili9882h/ats_ili9882_touch.o
adaptive-ts-${CONFIG_TOUCHSCREEN_ADAPTIVE_ILI9882H_SPI}-objs += vendors/ili9882h/ats_ili9882_spi.o
adaptive-ts-${CONFIG_TOUCHSCREEN_ADAPTIVE_ILI9882H_SPI}-objs += vendors/ili9882h/ats_ili9882_hostdl.o
adaptive-ts-${CONFIG_TOUCHSCREEN_ADAPTIVE_ICNL9911X}-objs += vendors/icnl9911x/ats_cts_driver.o
adaptive-ts-${CONFIG_TOUCHSCREEN_ADAPTIVE_ICNL9911X}-objs += vendors/icnl9911x/ats_cts_core.o
adaptive-ts-${CONFIG_TOUCHSCREEN_ADAPTIVE_ICNL9911X}-objs += vendors/icnl9911x/ats_cts_platform.o
adaptive-ts-${CONFIG_TOUCHSCREEN_ADAPTIVE_ICNL9911X}-objs += vendors/icnl9911x/ats_cts_sfctrlv2.o
adaptive-ts-${CONFIG_TOUCHSCREEN_ADAPTIVE_ICNL9911X}-objs += vendors/icnl9911x/ats_cts_spi_flash.o
adaptive-ts-${CONFIG_TOUCHSCREEN_ADAPTIVE_ICNL9911X}-objs += vendors/icnl9911x/ats_cts_firmware.o
adaptive-ts-${CONFIG_TOUCHSCREEN_ADAPTIVE_ICNL9911X}-objs += vendors/icnl9911x/ats_cts_tool.o
adaptive-ts-${CONFIG_TOUCHSCREEN_ADAPTIVE_ICNL9911X}-objs += vendors/icnl9911x/ats_cts_sysfs.o
adaptive-ts-${CONFIG_TOUCHSCREEN_ADAPTIVE_ICNL9911X}-objs += vendors/icnl9911x/ats_cts_test.o
adaptive-ts-${CONFIG_TOUCHSCREEN_ADAPTIVE_ICNL9911X}-objs += vendors/icnl9911x/ats_cts_charger_detect.o
adaptive-ts-${CONFIG_TOUCHSCREEN_ADAPTIVE_ICNL9911X}-objs += vendors/icnl9911x/ats_cts_earjack_detect.o
adaptive-ts-${CONFIG_TOUCHSCREEN_ADAPTIVE_ICNL9911X}-objs += vendors/icnl9911x/ats_cts_strerror.o
adaptive-ts-${CONFIG_TOUCHSCREEN_ADAPTIVE_ICNL9911X}-objs += vendors/icnl9911x/ats_icnl9911x.o
adaptive-ts-${CONFIG_TOUCHSCREEN_ADAPTIVE_FT8722}-objs += vendors/focaltech/ats_focaltech.o
adaptive-ts-${CONFIG_TOUCHSCREEN_ADAPTIVE_FT8722}-objs += vendors/focaltech/focaltech_core.o
adaptive-ts-${CONFIG_TOUCHSCREEN_ADAPTIVE_FT8722}-objs += vendors/focaltech/focaltech_esdcheck.o
adaptive-ts-${CONFIG_TOUCHSCREEN_ADAPTIVE_FT8722}-objs += vendors/focaltech/focaltech_ex_fun.o
adaptive-ts-${CONFIG_TOUCHSCREEN_ADAPTIVE_FT8722}-objs += vendors/focaltech/focaltech_ex_mode.o
adaptive-ts-${CONFIG_TOUCHSCREEN_ADAPTIVE_FT8722}-objs += vendors/focaltech/focaltech_flash/focaltech_upgrade_ft8722.o
adaptive-ts-${CONFIG_TOUCHSCREEN_ADAPTIVE_FT8722}-objs += vendors/focaltech/focaltech_flash/focaltech_upgrade_ft8006s_aa.o
adaptive-ts-${CONFIG_TOUCHSCREEN_ADAPTIVE_FT8722}-objs += vendors/focaltech/focaltech_flash.o
adaptive-ts-${CONFIG_TOUCHSCREEN_ADAPTIVE_FT8722}-objs += vendors/focaltech/focaltech_gesture.o
adaptive-ts-${CONFIG_TOUCHSCREEN_ADAPTIVE_FT8722}-objs += vendors/focaltech/focaltech_i2c.o
adaptive-ts-${CONFIG_TOUCHSCREEN_ADAPTIVE_FT8722}-objs += vendors/focaltech/focaltech_point_report_check.o


# adaptive-ts-${CONFIG_TOUCHSCREEN_ADAPTIVE_FT6336U}-objs += vendors/ats_ft6336u.o

ifeq ($(CONFIG_TOUCHSCREEN_ADAPTIVE_NT36XXX), y)
	CFLAGS_ats_nt36xxx_mp_ctrlram.o := -I$(src)/vendors/nt36xxx/$(BSP_BOARD_NAME)/
endif
ifeq ($(CONFIG_TOUCHSCREEN_ADAPTIVE_NT36XXX_SPI), y)
	CFLAGS_ats_nt36xxx_mp_ctrlram.o := -I$(src)/vendors/nt36xxx_spi/$(BSP_BOARD_NAME)/
endif

adaptive-ts-objs += $(adaptive-ts-y-objs)

