# SPDX-License-Identifier: GPL-2.0
#
# Makefile for the Linux network device drivers.
#

#
# Networking Core Drivers
#
obj-y += seth/

#
# Sipa sys Drivers
#
obj-$(CONFIG_SPRD_IPA_SYS) += sipa_sys/

#
# Sipa core Drivers
#
obj-$(CONFIG_SPRD_IPA_V3) += sipa_v3/

#
# Sipa delegate Drivers
#
obj-$(CONFIG_SPRD_IPA_DELEGATE) += sipa_delegate/
