/*
 * Copyright (C) 2021-2022 UNISOC Communications Inc.
 *
 * This software is licensed under the terms of the GNU General Public
 * License version 2, as published by the Free Software Foundation, and
 * may be copied, distributed, and modified under those terms.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 */

#ifndef _ISP_REG_H_
#define _ISP_REG_H_

#define ISP_MAX_COUNT                           1
#define ISP_LOGICAL_COUNT                       3
#define ISP_CONTEXT_MAX                         4
#define  ISP_CONTEXT_SW_MAX                     9

extern uint32_t s_isp_irq_no[ISP_LOGICAL_COUNT];
extern unsigned long s_isp_regbase[ISP_MAX_COUNT];
extern unsigned long isp_phys_base[ISP_MAX_COUNT];
extern unsigned long *isp_cfg_poll_addr[ISP_CONTEXT_SW_MAX];
extern unsigned long s_isp_mmubase;

#define ISP_PHYS_ADDR(idx)                      (isp_phys_base[idx])

#define ISP_P0_INT_BASE                         (0x0000UL)
#define ISP_P1_INT_BASE                         (0x0D00UL)
#define ISP_C0_INT_BASE                         (0x0E00UL)
#define ISP_C1_INT_BASE                         (0x0F00UL)
#define ISP_DEC_INT_BASE                        (0x0B00UL)

#define ISP_INT_STATUS                          (0x0000UL)
#define ISP_INT_STATUS1                         (0x0004UL)
#define ISP_INT_EN0                             (0x0010UL)
#define ISP_INT_CLR0                            (0x0014UL)
#define ISP_INT_RAW0                            (0x0018UL)
#define ISP_INT_INT0                            (0x001CUL)
#define ISP_INT_EN1                             (0x0020UL)
#define ISP_INT_CLR1                            (0x0024UL)
#define ISP_INT_RAW1                            (0x0028UL)
#define ISP_INT_INT1                            (0x002CUL)
#define ISP_INT_ALL_DONE_CTRL                   (0x0030UL)
#define ISP_INT_SKIP_CTRL                       (0x0034UL)
#define ISP_INT_SKIP_CTRL1                      (0x0038UL)
#define ISP_INT_ALL_DONE_SRC_CTRL               (0x003CUL)

#define ISP_FETCH_BASE                          (0x0100UL)
#define PYR_DEC_FETCH_BASE                      (0x8000UL)
#define PYR_REC_CUR_FETCH_BASE                  (0x9300UL)

#define ISP_FETCH_PARAM0                        (0x0010UL)
#define ISP_FETCH_MEM_SLICE_SIZE                (0x0014UL)
#define ISP_FETCH_SLICE_Y_ADDR                  (0x0018UL)
#define ISP_FETCH_SLICE_Y_PITCH                 (0x001CUL)
#define ISP_FETCH_SLICE_U_ADDR                  (0x0020UL)
#define ISP_FETCH_SLICE_U_PITCH                 (0x0024UL)
#define ISP_FETCH_MIPI_PARAM                    (0x0028UL)
#define ISP_FETCH_PARAM1                        (0x002CUL)
#define ISP_FETCH_START                         (0x0030UL)
#define ISP_FETCH_MIPI_PARAM_UV                 (0x0034UL)

#define ISP_DISPATCH_BASE                       (0x0300UL)
#define PYR_DEC_DISPATCH_BASE                   (0x8200UL)

#define ISP_DISPATCH_CH0_BAYER                  (0x0010UL)
#define ISP_DISPATCH_CH0_SIZE                   (0x0014UL)
#define ISP_DISPATCH_DLY                        (0x0018UL)
#define ISP_DISPATCH_LINE_DLY1                  (0x001CUL)
#define ISP_DISPATCH_PIPE_BUF_CTRL_CH0          (0x0020UL)
#define ISP_DISPATCH_CHK_SUM                    (0x0024UL)

#define ISP_COMMON_BASE                         (0x0700UL)
#define ISP_COMMON_SPACE_SEL                    (ISP_COMMON_BASE + 0x0010UL)
#define ISP_COMMON_SCL_PATH_SEL                 (ISP_COMMON_BASE + 0x0014UL)
/* fmcu c*/
#define ISP_COMMON_FMCU0_PATH_SEL               (ISP_COMMON_BASE + 0x0018UL)
#define ISP_COMMON_GCLK_CTRL_0                  (ISP_COMMON_BASE + 0x001CUL)
#define ISP_COMMON_GCLK_CTRL_1                  (ISP_COMMON_BASE + 0x0020UL)
#define ISP_COMMON_GCLK_CTRL_2                  (ISP_COMMON_BASE + 0x0024UL)
#define ISP_COMMON_GCLK_CTRL_3                  (ISP_COMMON_BASE + 0x0028UL)
/* fmcu p0*/
#define ISP_COMMON_FMCU1_PATH_SEL               (ISP_COMMON_BASE + 0x002CUL)
#define ISP_COMMON_SHADOW_CTRL_CH0              (ISP_COMMON_BASE + 0x0030UL)
#define ISP_COMMON_PMU_RAM_MASK                 (ISP_COMMON_BASE + 0x0034UL)
#define ISP_COMMON_WORK_CTRL                    (ISP_COMMON_BASE + 0x0038UL)
/* fmcu p1*/
#define ISP_COMMON_FMCU2_PATH_SEL               (ISP_COMMON_BASE + 0x003CUL)
#define ISP_COMMON_FMCU_P1_STATUS0              (ISP_COMMON_BASE + 0X004CUL)
#define ISP_COMMON_YDELAY_STATUS4               (ISP_COMMON_BASE + 0X03FCUL)

#define ISP_CORE_BASE                           (0x7400UL)
#define ISP_CORE_STATUS                         (ISP_CORE_BASE + 0x0000UL)
#define ISP_CORE_PMU_EN                         (ISP_CORE_BASE + 0x0010UL)
#define ISP_CORE_BUSY_ON                        (ISP_CORE_BASE + 0x0014UL)

#define ISP_CFG_BASE                            (0x7700UL)
#define ISP_CFG_STATUS0                         (ISP_CFG_BASE + 0x0000UL)
#define ISP_CFG_STATUS1                         (ISP_CFG_BASE + 0x0004UL)
#define ISP_CFG_STATUS2                         (ISP_CFG_BASE + 0x0008UL)
#define ISP_CFG_STATUS3                         (ISP_CFG_BASE + 0x000CUL)
#define ISP_CFG_PAMATER                         (ISP_CFG_BASE + 0x0010UL)
#define ISP_CFG_TM_NUM                          (ISP_CFG_BASE + 0x0014UL)
#define ISP_CFG_CAP0_TH                         (ISP_CFG_BASE + 0x0018UL)
#define ISP_CFG_CAP1_TH                         (ISP_CFG_BASE + 0x001CUL)
#define ISP_CFG_PRE0_CMD_ADDR                   (ISP_CFG_BASE + 0x0020UL)
#define ISP_CFG_PRE1_CMD_ADDR                   (ISP_CFG_BASE + 0x0024UL)
#define ISP_CFG_CAP0_CMD_ADDR                   (ISP_CFG_BASE + 0x0028UL)
#define ISP_CFG_CAP1_CMD_ADDR                   (ISP_CFG_BASE + 0x002CUL)
#define ISP_CFG_PRE0_START                      (ISP_CFG_BASE + 0x0030UL)
#define ISP_CFG_PRE1_START                      (ISP_CFG_BASE + 0x0034UL)
#define ISP_CFG_CAP0_START                      (ISP_CFG_BASE + 0x0038UL)
#define ISP_CFG_CAP1_START                      (ISP_CFG_BASE + 0x003CUL)
#define ISP_CFG_AUTO_CG_EN                      (ISP_CFG_BASE + 0x0040UL)
#define ISP_CFG_CAP_FMCU_RDY                    (ISP_CFG_BASE + 0x0044UL)
#define ISP_CFG0_BUF                            (0X1D000UL)

#define ISP_FMCU0_BASE                          (0x7500UL)
#define ISP_FMCU1_BASE                          (0x7600UL)
#define ISP_FMCU_DEC_BASE                       (0x7800UL)
#define ISP_FMCU_PRE1_BASE                      (0x7900UL)

#define ISP_FMCU_CTRL                           (0x0014UL)
#define ISP_FMCU_DDR_ADDR                       (0x0018UL)
#define ISP_FMCU_AHB_ARB                        (0x001CUL)
#define ISP_FMCU_START                          (0x0020UL)
#define ISP_FMCU_TIME_OUT_THD                   (0x0024UL)
#define ISP_FMCU_CMD_READY                      (0x0028UL)
#define ISP_FMCU_ISP_REG_REGION                 (0x002CUL)
#define ISP_FMCU_STOP                           (0x0034UL)
#define ISP_FMCU_SW_TRIGGER                     (0x003CUL)
#define ISP_FMCU_CMD                            (0xF030UL)

#define ISP_CFAE_BASE                           (0x3400UL)
#define ISP_CFAE_NEW_CFG0                       (ISP_CFAE_BASE + 0x3010UL)
#define ISP_CFAE_INTP_CFG0                      (ISP_CFAE_BASE + 0x3014UL)
#define ISP_CFAE_INTP_CFG1                      (ISP_CFAE_BASE + 0x3018UL)
#define ISP_CFAE_INTP_CFG2                      (ISP_CFAE_BASE + 0x301CUL)
#define ISP_CFAE_INTP_CFG3                      (ISP_CFAE_BASE + 0x3020UL)
#define ISP_CFAE_INTP_CFG4                      (ISP_CFAE_BASE + 0x3024UL)
#define ISP_CFAE_INTP_CFG5                      (ISP_CFAE_BASE + 0x3028UL)
#define ISP_CFAE_CSS_CFG0                       (ISP_CFAE_BASE + 0x302CUL)
#define ISP_CFAE_CSS_CFG1                       (ISP_CFAE_BASE + 0x3030UL)
#define ISP_CFAE_CSS_CFG2                       (ISP_CFAE_BASE + 0x3034UL)
#define ISP_CFAE_CSS_CFG3                       (ISP_CFAE_BASE + 0x3038UL)
#define ISP_CFAE_CSS_CFG4                       (ISP_CFAE_BASE + 0x303CUL)
#define ISP_CFAE_CSS_CFG5                       (ISP_CFAE_BASE + 0x3040UL)
#define ISP_CFAE_CSS_CFG6                       (ISP_CFAE_BASE + 0x3044UL)
#define ISP_CFAE_CSS_CFG7                       (ISP_CFAE_BASE + 0x3048UL)
#define ISP_CFAE_CSS_CFG8                       (ISP_CFAE_BASE + 0x304CUL)
#define ISP_CFAE_CSS_CFG9                       (ISP_CFAE_BASE + 0x3050UL)
#define ISP_CFAE_CSS_CFG10                      (ISP_CFAE_BASE + 0x3054UL)
#define ISP_CFAE_CSS_CFG11                      (ISP_CFAE_BASE + 0x3058UL)

#define ISP_HSV_BASE                            (0x3300UL)
#define ISP_HSV_PARAM                           (ISP_HSV_BASE + 0x0010UL)
#define ISP_HSV_CFG0                            (ISP_HSV_BASE + 0x0014UL)
#define ISP_HSV_CFG1                            (ISP_HSV_BASE + 0x0018UL)
#define ISP_HSV_CFG2                            (ISP_HSV_BASE + 0x001CUL)
#define ISP_HSV_CFG3                            (ISP_HSV_BASE + 0x0020UL)
#define ISP_HSV_CFG4                            (ISP_HSV_BASE + 0x0024UL)
#define ISP_HSV_CFG5                            (ISP_HSV_BASE + 0x0028UL)
#define ISP_HSV_CFG6                            (ISP_HSV_BASE + 0x002CUL)
#define ISP_HSV_CFG7                            (ISP_HSV_BASE + 0x0030UL)
#define ISP_HSV_CFG8                            (ISP_HSV_BASE + 0x0034UL)
#define ISP_HSV_CFG9                            (ISP_HSV_BASE + 0x0038UL)
#define ISP_HSV_CFG10                           (ISP_HSV_BASE + 0x003CUL)
#define ISP_HSV_CFG11                           (ISP_HSV_BASE + 0x0040UL)
#define ISP_HSV_CFG12                           (ISP_HSV_BASE + 0x0044UL)
#define ISP_HSV_CFG13                           (ISP_HSV_BASE + 0x0048UL)
#define ISP_HSV_CFG14                           (ISP_HSV_BASE + 0x004CUL)
#define ISP_HSV_CFG15                           (ISP_HSV_BASE + 0x0050UL)
#define ISP_HSV_CFG16                           (ISP_HSV_BASE + 0x0054UL)
#define ISP_HSV_CFG17                           (ISP_HSV_BASE + 0x0058UL)
#define ISP_HSV_CFG18                           (ISP_HSV_BASE + 0x005cUL)
#define ISP_HSV_CFG19                           (ISP_HSV_BASE + 0x0060UL)
#define ISP_HSV_CFG20                           (ISP_HSV_BASE + 0x0064UL)
#define ISP_HSV_CFG21                           (ISP_HSV_BASE + 0x0068UL)
#define ISP_HSV_TABLEA_BUF0_CH0                 (0x18000UL)
#define ISP_HSV_TABLEB_BUF0_CH0                 (0x18400UL)
#define ISP_HSV_TABLEC_BUF0_CH0                 (0x18800UL)
#define ISP_HSV_TABLED_BUF0_CH0                 (0x18C00UL)
#define ISP_HSV_BUF0_CH0                        (0x18000UL)

#define ISP_CTM_BASE                            (0x3400UL)
#define ISP_CTM_PARAM                           (ISP_CTM_BASE + 0x0010UL)
#define ISP_3D_LUT_BUF0_CH0                     (0x1B000UL)

#define ISP_RGB2YUV420_BASE                     (0x3500UL)
#define ISP_RGB2YUV420_PARAM                    (ISP_RGB2YUV420_BASE + 0x0010UL)
#define ISP_RGB2YUV420_MATRIX0                  (ISP_RGB2YUV420_BASE + 0x0014UL)
#define ISP_RGB2YUV420_MATRIX1                  (ISP_RGB2YUV420_BASE + 0x0018UL)
#define ISP_RGB2YUV420_MATRIX2                  (ISP_RGB2YUV420_BASE + 0x001CUL)
#define ISP_RGB2YUV420_MATRIX3                  (ISP_RGB2YUV420_BASE + 0x0020UL)
#define ISP_RGB2YUV420_MATRIX4                  (ISP_RGB2YUV420_BASE + 0x0024UL)
#define ISP_RGB2YUV420_SHIFT0                   (ISP_RGB2YUV420_BASE + 0x0028UL)
#define ISP_RGB2YUV420_SHIFT1                   (ISP_RGB2YUV420_BASE + 0x002CUL)

#define ISP_UVD_BASE                            (0x1100UL)
#define ISP_UVD_PARAM                           (ISP_UVD_BASE + 0x0010UL)
#define ISP_UVD_PARAM0                          (ISP_UVD_BASE + 0x0014UL)
#define ISP_UVD_PARAM1                          (ISP_UVD_BASE + 0x0018UL)
#define ISP_UVD_PARAM2                          (ISP_UVD_BASE + 0x001CUL)
#define ISP_UVD_PARAM3                          (ISP_UVD_BASE + 0x0020UL)
#define ISP_UVD_PARAM4                          (ISP_UVD_BASE + 0x0024UL)
#define ISP_UVD_PARAM5                          (ISP_UVD_BASE + 0x0028UL)
#define ISP_UVD_PARAM6                          (ISP_UVD_BASE + 0x002CUL)

#define ISP_LTM_HISTS_FRGB_BASE                 (0x3100UL)
#define ISP_LTM_PARAMETERS                      (ISP_LTM_HISTS_FRGB_BASE + 0x0010UL)
#define ISP_LTM_ROI_START                       (ISP_LTM_HISTS_FRGB_BASE + 0x0014UL)
#define ISP_LTM_TILE_RANGE                      (ISP_LTM_HISTS_FRGB_BASE + 0x0018UL)
#define ISP_LTM_CLIP_LIMIT                      (ISP_LTM_HISTS_FRGB_BASE + 0x001CUL)
#define ISP_LTM_THRES                           (ISP_LTM_HISTS_FRGB_BASE + 0x0020UL)
#define ISP_LTM_ADDR                            (ISP_LTM_HISTS_FRGB_BASE + 0x0024UL)
#define ISP_LTM_PITCH                           (ISP_LTM_HISTS_FRGB_BASE + 0x0028UL)
#define ISP_LTM_RGB_HIST_BUF0_ADDR              (0x1A000UL)

#define ISP_LTM_MAP_RGB_BASE                    (0x3200UL)
#define ISP_LTM_MAP_PARAM0                      (ISP_LTM_MAP_RGB_BASE + 0x0010UL)
#define ISP_LTM_MAP_PARAM1                      (ISP_LTM_MAP_RGB_BASE + 0x0014UL)
#define ISP_LTM_MAP_PARAM2                      (ISP_LTM_MAP_RGB_BASE + 0x0018UL)
#define ISP_LTM_MAP_PARAM3                      (ISP_LTM_MAP_RGB_BASE + 0x001CUL)
#define ISP_LTM_MAP_PARAM4                      (ISP_LTM_MAP_RGB_BASE + 0x0020UL)
#define ISP_LTM_MAP_PARAM5                      (ISP_LTM_MAP_RGB_BASE + 0x0024UL)

#define ISP_CDN_BASE                            (0x4000UL)
#define ISP_CDN_PARAM                           (ISP_CDN_BASE + 0x0010UL)
#define ISP_CDN_THRUV                           (ISP_CDN_BASE + 0x0014UL)
#define ISP_CDN_U_RANWEI_0                      (ISP_CDN_BASE + 0x0018UL)
#define ISP_CDN_U_RANWEI_1                      (ISP_CDN_BASE + 0x001CUL)
#define ISP_CDN_U_RANWEI_2                      (ISP_CDN_BASE + 0x0020UL)
#define ISP_CDN_U_RANWEI_3                      (ISP_CDN_BASE + 0x0024UL)
#define ISP_CDN_U_RANWEI_4                      (ISP_CDN_BASE + 0x0028UL)
#define ISP_CDN_U_RANWEI_5                      (ISP_CDN_BASE + 0x002CUL)
#define ISP_CDN_U_RANWEI_6                      (ISP_CDN_BASE + 0x0030UL)
#define ISP_CDN_U_RANWEI_7                      (ISP_CDN_BASE + 0x0034UL)
#define ISP_CDN_V_RANWEI_0                      (ISP_CDN_BASE + 0x0038UL)
#define ISP_CDN_V_RANWEI_1                      (ISP_CDN_BASE + 0x003CUL)
#define ISP_CDN_V_RANWEI_2                      (ISP_CDN_BASE + 0x0040UL)
#define ISP_CDN_V_RANWEI_3                      (ISP_CDN_BASE + 0x0044UL)
#define ISP_CDN_V_RANWEI_4                      (ISP_CDN_BASE + 0x0048UL)
#define ISP_CDN_V_RANWEI_5                      (ISP_CDN_BASE + 0x004CUL)
#define ISP_CDN_V_RANWEI_6                      (ISP_CDN_BASE + 0x0050UL)
#define ISP_CDN_V_RANWEI_7                      (ISP_CDN_BASE + 0x0054UL)

#define ISP_EE_BASE                             (0x4200UL)
#define ISP_EE_PARAM                            (ISP_EE_BASE + 0x0010UL)
#define ISP_EE_CFG0                             (ISP_EE_BASE + 0x0014UL)
#define ISP_EE_IPD_CFG0                         (ISP_EE_BASE + 0x002CUL)
#define ISP_EE_IPD_CFG1                         (ISP_EE_BASE + 0x0030UL)
#define ISP_EE_IPD_CFG2                         (ISP_EE_BASE + 0x0034UL)
#define ISP_EE_LUM_CFG0                         (ISP_EE_BASE + 0x0038UL)
#define ISP_EE_LUM_CFG1                         (ISP_EE_BASE + 0x003CUL)
#define ISP_EE_LUM_CFG2                         (ISP_EE_BASE + 0x0040UL)
#define ISP_EE_LUM_CFG3                         (ISP_EE_BASE + 0x0044UL)
#define ISP_EE_LUM_CFG4                         (ISP_EE_BASE + 0x0048UL)
#define ISP_EE_LUM_CFG5                         (ISP_EE_BASE + 0x004CUL)
#define ISP_EE_LUM_CFG6                         (ISP_EE_BASE + 0x0050UL)
#define ISP_EE_LUM_CFG7                         (ISP_EE_BASE + 0x0054UL)
#define ISP_EE_LUM_CFG8                         (ISP_EE_BASE + 0x0058UL)
#define ISP_EE_LUM_CFG9                         (ISP_EE_BASE + 0x005CUL)
#define ISP_EE_LUM_CFG10                        (ISP_EE_BASE + 0x0060UL)
#define ISP_EE_LUM_CFG11                        (ISP_EE_BASE + 0x0064UL)
#define ISP_EE_LUM_CFG12                        (ISP_EE_BASE + 0x0068UL)
#define ISP_EE_LUM_CFG13                        (ISP_EE_BASE + 0x006CUL)
#define ISP_EE_LUM_CFG14                        (ISP_EE_BASE + 0x0070UL)
#define ISP_EE_LUM_CFG15                        (ISP_EE_BASE + 0x0074UL)
#define ISP_EE_LUM_CFG16                        (ISP_EE_BASE + 0x0078UL)
#define ISP_EE_LUM_CFG17                        (ISP_EE_BASE + 0x007CUL)
#define ISP_EE_LUM_CFG18                        (ISP_EE_BASE + 0x0080UL)
#define ISP_EE_RATIO                            (ISP_EE_BASE + 0x0084UL)
#define ISP_EE_OFFSET_THR_LAYER0_POS            (ISP_EE_BASE + 0x0088UL)
#define ISP_EE_OFFSET_RATIO_LAYER0_CURVE_POS    (ISP_EE_BASE + 0x008CUL)
#define ISP_EE_OFFSET_CLIP_LAYER0_POS           (ISP_EE_BASE + 0x0090UL)
#define ISP_EE_OFFSET_THR_LAYER0_NEG            (ISP_EE_BASE + 0x0094UL)
#define ISP_EE_OFFSET_RATIO_LAYER0_CURVE_NEG    (ISP_EE_BASE + 0x0098UL)
#define ISP_EE_OFFSET_CLIP_LAYER0_CURVE_NEG     (ISP_EE_BASE + 0x009CUL)
#define ISP_EE_OFFSET_RATIO_LAYER0_LUM_CURVE    (ISP_EE_BASE + 0x00A0UL)
#define ISP_EE_OFFSET_RATIO_LAYER0_FREQ_CURVE   (ISP_EE_BASE + 0x00A4UL)
#define ISP_EE_OFFSET_THR_LAYER1_POS            (ISP_EE_BASE + 0x00A8UL)
#define ISP_EE_OFFSET_RATIO_LAYER1_CURVE_POS    (ISP_EE_BASE + 0x00ACUL)
#define ISP_EE_OFFSET_CLIP_LAYER1_POS           (ISP_EE_BASE + 0x00B0UL)
#define ISP_EE_OFFSET_THR_LAYER1_NEG            (ISP_EE_BASE + 0x00B4UL)
#define ISP_EE_OFFSET_RATIO_LAYER1_CURVE_NEG    (ISP_EE_BASE + 0x00B8UL)
#define ISP_EE_OFFSET_CLIP_LAYER1_CURVE_NEG     (ISP_EE_BASE + 0x00BCUL)
#define ISP_EE_OFFSET_RATIO_LAYER1_LUM_CURVE    (ISP_EE_BASE + 0x00C0UL)
#define ISP_EE_OFFSET_RATIO_LAYER1_FREQ_CURVE   (ISP_EE_BASE + 0x00C4UL)
#define ISP_EE_OFFSET_THR_LAYER2_POS            (ISP_EE_BASE + 0x00C8UL)
#define ISP_EE_OFFSET_RATIO_LAYER2_CURVE_POS    (ISP_EE_BASE + 0x00CCUL)
#define ISP_EE_OFFSET_CLIP_LAYER2_POS           (ISP_EE_BASE + 0x00D0UL)
#define ISP_EE_OFFSET_THR_LAYER2_NEG            (ISP_EE_BASE + 0x00D4UL)
#define ISP_EE_OFFSET_RATIO_LAYER2_CURVE_NEG    (ISP_EE_BASE + 0x00D8UL)
#define ISP_EE_OFFSET_CLIP_LAYER2_CURVE_NEG     (ISP_EE_BASE + 0x00DCUL)
#define ISP_EE_OFFSET_RATIO_LAYER2_LUM_CURVE    (ISP_EE_BASE + 0x00E0UL)
#define ISP_EE_OFFSET_RATIO_LAYER2_FREQ_CURVE   (ISP_EE_BASE + 0x00E4UL)
#define ISP_EE_IPD_THR                          (ISP_EE_BASE + 0x00E8UL)
#define ISP_EE_HOP_CFG0                         (ISP_EE_BASE + 0x00ECUL)
#define ISP_EE_HOP_CFG1                         (ISP_EE_BASE + 0x00F0UL)
#define ISP_EE_OFFSET_GRAD_CFG0                 (ISP_EE_BASE + 0x00F4UL)
#define ISP_EE_OFFSET_GRAD_CFG1                 (ISP_EE_BASE + 0x00F8UL)
#define ISP_EE_OFFSET_GRAD_CFG2                 (ISP_EE_BASE + 0x00FCUL)
#define ISP_EE_OFFSET_GRAD_CFG3                 (ISP_EE_BASE + 0x0100UL)
#define ISP_EE_GRAD_RATIO_THR                   (ISP_EE_BASE + 0x0104UL)
#define ISP_EE_PYRAMID_RATIO_THR                (ISP_EE_BASE + 0x0108UL)
#define ISP_EE_PIXEL_POSTION                    (ISP_EE_BASE + 0x010CUL)
#define ISP_EE_PYRAMID_OFFSET_COEF0             (ISP_EE_BASE + 0x0110UL)
#define ISP_EE_PYRAMID_OFFSET_COEF1             (ISP_EE_BASE + 0x0114UL)
#define ISP_EE_RATIO_COEF                       (ISP_EE_BASE + 0x0118UL)
#define ISP_EE_PYRAMID_OFFSET_THR               (ISP_EE_BASE + 0x011CUL)
#define ISP_EE_PYRAMID_OFFSET_GAIN_MIN0         (ISP_EE_BASE + 0x0120UL)
#define ISP_EE_PYRAMID_OFFSET_GAIN_MIN1         (ISP_EE_BASE + 0x0124UL)
#define ISP_EE_GLOBAL_POSTION                   (ISP_EE_BASE + 0x0128UL)

#define ISP_YGAMMA_BASE                         (0x4100UL)
#define ISP_YGAMMA_PARAM                        (ISP_YGAMMA_BASE + 0x0010UL)
#define ISP_YGAMMA_BUF0_CH0                     (0x19600UL)

#define ISP_YDELAY_BASE                         (0x1600UL)
#define ISP_YDELAY_PARAM                        (ISP_YDELAY_BASE + 0x0010UL)
#define ISP_YDELAY_STEP                         (ISP_YDELAY_BASE + 0x0014UL)

#define ISP_CNR_BASE                            (0x1700UL)
#define ISP_YUV_CNR_CONTRL0                     (ISP_CNR_BASE + 0x0010UL)
#define ISP_YUV_CNR_CONTRL1                     (ISP_CNR_BASE + 0x0014UL)
#define ISP_YUV_CNR_CFG0                        (ISP_CNR_BASE + 0x0018UL)
#define ISP_YUV_CNR_CFG1                        (ISP_CNR_BASE + 0x001CUL)
#define ISP_YUV_CNR_CFG2                        (ISP_CNR_BASE + 0x0020UL)
#define ISP_YUV_CNR_RESERVED1                   (ISP_CNR_BASE + 0x0024UL)
#define ISP_YUV_CNR_RESERVED2                   (ISP_CNR_BASE + 0x0028UL)
#define ISP_YUV_CNR_RESERVED3                   (ISP_CNR_BASE + 0x002CUL)
#define ISP_YUV_CNR_RESERVED4                   (ISP_CNR_BASE + 0x0030UL)
#define ISP_YUV_CNR_RESERVED5                   (ISP_CNR_BASE + 0x0034UL)
#define ISP_YUV_CNR_RESERVED6                   (ISP_CNR_BASE + 0x0038UL)
#define ISP_YUV_CNR_RESERVED7                   (ISP_CNR_BASE + 0x003CUL)
#define ISP_YUV_CNR_Y_L0_WHT0                   (ISP_CNR_BASE + 0x0040UL)
#define ISP_YUV_CNR_Y_L0_WHT1                   (ISP_CNR_BASE + 0x0044UL)
#define ISP_YUV_CNR_Y_L0_WHT2                   (ISP_CNR_BASE + 0x0048UL)
#define ISP_YUV_CNR_Y_L0_WHT3                   (ISP_CNR_BASE + 0x004CUL)
#define ISP_YUV_CNR_Y_L0_WHT4                   (ISP_CNR_BASE + 0x0050UL)
#define ISP_YUV_CNR_Y_L0_WHT5                   (ISP_CNR_BASE + 0x0054UL)
#define ISP_YUV_CNR_Y_L0_WHT6                   (ISP_CNR_BASE + 0x0058UL)
#define ISP_YUV_CNR_Y_L0_WHT7                   (ISP_CNR_BASE + 0x005CUL)
#define ISP_YUV_CNR_Y_L0_WHT8                   (ISP_CNR_BASE + 0x0060UL)
#define ISP_YUV_CNR_Y_L0_WHT9                   (ISP_CNR_BASE + 0x0064UL)
#define ISP_YUV_CNR_Y_L0_WHT10                  (ISP_CNR_BASE + 0x0068UL)
#define ISP_YUV_CNR_Y_L0_WHT11                  (ISP_CNR_BASE + 0x006CUL)
#define ISP_YUV_CNR_Y_L0_WHT12                  (ISP_CNR_BASE + 0x0070UL)
#define ISP_YUV_CNR_Y_L0_WHT13                  (ISP_CNR_BASE + 0x0074UL)
#define ISP_YUV_CNR_Y_L0_WHT14                  (ISP_CNR_BASE + 0x0078UL)
#define ISP_YUV_CNR_Y_L0_WHT15                  (ISP_CNR_BASE + 0x007CUL)
#define ISP_YUV_CNR_Y_L0_WHT16                  (ISP_CNR_BASE + 0x0080UL)
#define ISP_YUV_CNR_Y_L0_WHT17                  (ISP_CNR_BASE + 0x0084UL)
#define ISP_YUV_CNR_Y_L1_WHT0                   (ISP_CNR_BASE + 0x0088UL)
#define ISP_YUV_CNR_Y_L1_WHT1                   (ISP_CNR_BASE + 0x008cUL)
#define ISP_YUV_CNR_Y_L1_WHT2                   (ISP_CNR_BASE + 0x0090UL)
#define ISP_YUV_CNR_Y_L1_WHT3                   (ISP_CNR_BASE + 0x0094UL)
#define ISP_YUV_CNR_Y_L1_WHT4                   (ISP_CNR_BASE + 0x0098UL)
#define ISP_YUV_CNR_Y_L1_WHT5                   (ISP_CNR_BASE + 0x009CUL)
#define ISP_YUV_CNR_Y_L1_WHT6                   (ISP_CNR_BASE + 0x00A0UL)
#define ISP_YUV_CNR_Y_L1_WHT7                   (ISP_CNR_BASE + 0x00A4UL)
#define ISP_YUV_CNR_Y_L1_WHT8                   (ISP_CNR_BASE + 0x00A8UL)
#define ISP_YUV_CNR_Y_L1_WHT9                   (ISP_CNR_BASE + 0x00AcUL)
#define ISP_YUV_CNR_Y_L1_WHT10                  (ISP_CNR_BASE + 0x00B0UL)
#define ISP_YUV_CNR_Y_L1_WHT11                  (ISP_CNR_BASE + 0x00B4UL)
#define ISP_YUV_CNR_Y_L1_WHT12                  (ISP_CNR_BASE + 0x00B8UL)
#define ISP_YUV_CNR_Y_L1_WHT13                  (ISP_CNR_BASE + 0x00BCUL)
#define ISP_YUV_CNR_Y_L1_WHT14                  (ISP_CNR_BASE + 0x00C0UL)
#define ISP_YUV_CNR_Y_L1_WHT15                  (ISP_CNR_BASE + 0x00C4UL)
#define ISP_YUV_CNR_Y_L1_WHT16                  (ISP_CNR_BASE + 0x00C8UL)
#define ISP_YUV_CNR_Y_L1_WHT17                  (ISP_CNR_BASE + 0x00CCUL)
#define ISP_YUV_CNR_Y_L2_WHT0                   (ISP_CNR_BASE + 0x00D0UL)
#define ISP_YUV_CNR_Y_L2_WHT1                   (ISP_CNR_BASE + 0x00D4UL)
#define ISP_YUV_CNR_Y_L2_WHT2                   (ISP_CNR_BASE + 0x00D8UL)
#define ISP_YUV_CNR_Y_L2_WHT3                   (ISP_CNR_BASE + 0x00DCUL)
#define ISP_YUV_CNR_Y_L2_WHT4                   (ISP_CNR_BASE + 0x00E0UL)
#define ISP_YUV_CNR_Y_L2_WHT5                   (ISP_CNR_BASE + 0x00E4UL)
#define ISP_YUV_CNR_Y_L2_WHT6                   (ISP_CNR_BASE + 0x00E8UL)
#define ISP_YUV_CNR_Y_L2_WHT7                   (ISP_CNR_BASE + 0x00ECUL)
#define ISP_YUV_CNR_Y_L2_WHT8                   (ISP_CNR_BASE + 0x00F0UL)
#define ISP_YUV_CNR_Y_L2_WHT9                   (ISP_CNR_BASE + 0x00F4UL)
#define ISP_YUV_CNR_Y_L2_WHT10                  (ISP_CNR_BASE + 0x00F8UL)
#define ISP_YUV_CNR_Y_L2_WHT11                  (ISP_CNR_BASE + 0x00FCUL)
#define ISP_YUV_CNR_Y_L2_WHT12                  (ISP_CNR_BASE + 0x0100UL)
#define ISP_YUV_CNR_Y_L2_WHT13                  (ISP_CNR_BASE + 0x0104UL)
#define ISP_YUV_CNR_Y_L2_WHT14                  (ISP_CNR_BASE + 0x0108UL)
#define ISP_YUV_CNR_Y_L2_WHT15                  (ISP_CNR_BASE + 0x010CUL)
#define ISP_YUV_CNR_Y_L2_WHT16                  (ISP_CNR_BASE + 0x0110UL)
#define ISP_YUV_CNR_Y_L2_WHT17                  (ISP_CNR_BASE + 0x0114UL)
#define ISP_YUV_CNR_UV_L0_WHT0                  (ISP_CNR_BASE + 0x0118UL)
#define ISP_YUV_CNR_UV_L0_WHT1                  (ISP_CNR_BASE + 0x011CUL)
#define ISP_YUV_CNR_UV_L0_WHT2                  (ISP_CNR_BASE + 0x0120UL)
#define ISP_YUV_CNR_UV_L0_WHT3                  (ISP_CNR_BASE + 0x0124UL)
#define ISP_YUV_CNR_UV_L0_WHT4                  (ISP_CNR_BASE + 0x0128UL)
#define ISP_YUV_CNR_UV_L0_WHT5                  (ISP_CNR_BASE + 0x012CUL)
#define ISP_YUV_CNR_UV_L0_WHT6                  (ISP_CNR_BASE + 0x0130UL)
#define ISP_YUV_CNR_UV_L0_WHT7                  (ISP_CNR_BASE + 0x0134UL)
#define ISP_YUV_CNR_UV_L0_WHT8                  (ISP_CNR_BASE + 0x0138UL)
#define ISP_YUV_CNR_UV_L0_WHT9                  (ISP_CNR_BASE + 0x013CUL)
#define ISP_YUV_CNR_UV_L0_WHT10                 (ISP_CNR_BASE + 0x0140UL)
#define ISP_YUV_CNR_UV_L0_WHT11                 (ISP_CNR_BASE + 0x0144UL)
#define ISP_YUV_CNR_UV_L0_WHT12                 (ISP_CNR_BASE + 0x0148UL)
#define ISP_YUV_CNR_UV_L0_WHT13                 (ISP_CNR_BASE + 0x014CUL)
#define ISP_YUV_CNR_UV_L0_WHT14                 (ISP_CNR_BASE + 0x0150UL)
#define ISP_YUV_CNR_UV_L0_WHT15                 (ISP_CNR_BASE + 0x0154UL)
#define ISP_YUV_CNR_UV_L0_WHT16                 (ISP_CNR_BASE + 0x0158UL)
#define ISP_YUV_CNR_UV_L0_WHT17                 (ISP_CNR_BASE + 0x015CUL)
#define ISP_YUV_CNR_UV_L1_WHT0                  (ISP_CNR_BASE + 0x0160UL)
#define ISP_YUV_CNR_UV_L1_WHT1                  (ISP_CNR_BASE + 0x0164UL)
#define ISP_YUV_CNR_UV_L1_WHT2                  (ISP_CNR_BASE + 0x0168UL)
#define ISP_YUV_CNR_UV_L1_WHT3                  (ISP_CNR_BASE + 0x016CUL)
#define ISP_YUV_CNR_UV_L1_WHT4                  (ISP_CNR_BASE + 0x0170UL)
#define ISP_YUV_CNR_UV_L1_WHT5                  (ISP_CNR_BASE + 0x0174UL)
#define ISP_YUV_CNR_UV_L1_WHT6                  (ISP_CNR_BASE + 0x0178UL)
#define ISP_YUV_CNR_UV_L1_WHT7                  (ISP_CNR_BASE + 0x017CUL)
#define ISP_YUV_CNR_UV_L1_WHT8                  (ISP_CNR_BASE + 0x0180UL)
#define ISP_YUV_CNR_UV_L1_WHT9                  (ISP_CNR_BASE + 0x0184UL)
#define ISP_YUV_CNR_UV_L1_WHT10                 (ISP_CNR_BASE + 0x0188UL)
#define ISP_YUV_CNR_UV_L1_WHT11                 (ISP_CNR_BASE + 0x018CUL)
#define ISP_YUV_CNR_UV_L1_WHT12                 (ISP_CNR_BASE + 0x0190UL)
#define ISP_YUV_CNR_UV_L1_WHT13                 (ISP_CNR_BASE + 0x0194UL)
#define ISP_YUV_CNR_UV_L1_WHT14                 (ISP_CNR_BASE + 0x0198UL)
#define ISP_YUV_CNR_UV_L1_WHT15                 (ISP_CNR_BASE + 0x019CUL)
#define ISP_YUV_CNR_UV_L1_WHT16	                (ISP_CNR_BASE + 0x01A0UL)
#define ISP_YUV_CNR_UV_L1_WHT17                 (ISP_CNR_BASE + 0x01A4UL)
#define ISP_YUV_CNR_UV_L2_WHT0                  (ISP_CNR_BASE + 0x01A8UL)
#define ISP_YUV_CNR_UV_L2_WHT1                  (ISP_CNR_BASE + 0x01ACUL)
#define ISP_YUV_CNR_UV_L2_WHT2                  (ISP_CNR_BASE + 0x01B0UL)
#define ISP_YUV_CNR_UV_L2_WHT3                  (ISP_CNR_BASE + 0x01B4UL)
#define ISP_YUV_CNR_UV_L2_WHT4                  (ISP_CNR_BASE + 0x01B8UL)
#define ISP_YUV_CNR_UV_L2_WHT5                  (ISP_CNR_BASE + 0x01BCUL)
#define ISP_YUV_CNR_UV_L2_WHT6                  (ISP_CNR_BASE + 0x01C0UL)
#define ISP_YUV_CNR_UV_L2_WHT7                  (ISP_CNR_BASE + 0x01C4UL)
#define ISP_YUV_CNR_UV_L2_WHT8                  (ISP_CNR_BASE + 0x01C8UL)
#define ISP_YUV_CNR_UV_L2_WHT9                  (ISP_CNR_BASE + 0x01CCUL)
#define ISP_YUV_CNR_UV_L2_WHT10                 (ISP_CNR_BASE + 0x01D0UL)
#define ISP_YUV_CNR_UV_L2_WHT11                 (ISP_CNR_BASE + 0x01D4UL)
#define ISP_YUV_CNR_UV_L2_WHT12                 (ISP_CNR_BASE + 0x01D8UL)
#define ISP_YUV_CNR_UV_L2_WHT13                 (ISP_CNR_BASE + 0x01DCUL)
#define ISP_YUV_CNR_UV_L2_WHT14                 (ISP_CNR_BASE + 0x01E0UL)
#define ISP_YUV_CNR_UV_L2_WHT15                 (ISP_CNR_BASE + 0x01E4UL)
#define ISP_YUV_CNR_UV_L2_WHT16                 (ISP_CNR_BASE + 0x01E8UL)
#define ISP_YUV_CNR_UV_L2_WHT17                 (ISP_CNR_BASE + 0x01ECUL)

#define ISP_YUV420toRGB_BASE                    (0x3000UL)
#define ISP_YUV420toRGB_PARAM                   (ISP_YUV420toRGB_BASE + 0x0010UL)
#define ISP_YUV420toRGB_MATRIX0                 (ISP_YUV420toRGB_BASE + 0x0014UL)
#define ISP_YUV420toRGB_MATRIX1                 (ISP_YUV420toRGB_BASE + 0x0018UL)
#define ISP_YUV420toRGB_MATRIX2                 (ISP_YUV420toRGB_BASE + 0x001CUL)
#define ISP_YUV420toRGB_MATRIX3                 (ISP_YUV420toRGB_BASE + 0x0020UL)
#define ISP_YUV420toRGB_MATRIX4                 (ISP_YUV420toRGB_BASE + 0x0024UL)
#define ISP_YUV420toRGB_SHIFT0                  (ISP_YUV420toRGB_BASE + 0x0028UL)
#define ISP_YUV420toRGB_SHIFT1                  (ISP_YUV420toRGB_BASE + 0x002CUL)

#define ISP_YRANDOM_BASE                        (0x4400UL)
#define ISP_YRANDOM_PARAM1                      (ISP_YRANDOM_BASE + 0x0010UL)
#define ISP_YRANDOM_PARAM2                      (ISP_YRANDOM_BASE + 0x0014UL)
#define ISP_YRANDOM_PARAM3                      (ISP_YRANDOM_BASE + 0x0018UL)
#define ISP_YRANDOM_INIT                        (ISP_YRANDOM_BASE + 0x001cUL)

#define ISP_BCHS_BASE                           (0x4500UL)
#define ISP_BCHS_PARAM                          (ISP_BCHS_BASE + 0x0010UL)
#define ISP_CSA_FACTOR                          (ISP_BCHS_BASE + 0x0014UL)
#define ISP_HUA_FACTOR                          (ISP_BCHS_BASE + 0x0018UL)
#define ISP_BRTA_FACTOR                         (ISP_BCHS_BASE + 0x001cUL)
#define ISP_CNTA_FACTOR                         (ISP_BCHS_BASE + 0x0020UL)

#define ISP_3DNR_MEM_CTRL_BASE                  (0x2000UL)
#define ISP_3DNR_MEM_CTRL_PARAM0                (ISP_3DNR_MEM_CTRL_BASE + 0x0010UL)
#define ISP_3DNR_MEM_CTRL_PARAM1                (ISP_3DNR_MEM_CTRL_BASE + 0x0018UL)
#define ISP_3DNR_MEM_CTRL_PARAM2                (ISP_3DNR_MEM_CTRL_BASE + 0x001CUL)
#define ISP_3DNR_MEM_CTRL_PARAM3                (ISP_3DNR_MEM_CTRL_BASE + 0x0020UL)
#define ISP_3DNR_MEM_CTRL_PARAM4                (ISP_3DNR_MEM_CTRL_BASE + 0x0024UL)
#define ISP_3DNR_MEM_CTRL_PARAM5                (ISP_3DNR_MEM_CTRL_BASE + 0x0028UL)
#define ISP_3DNR_MEM_CTRL_PARAM7                (ISP_3DNR_MEM_CTRL_BASE + 0x002CUL)
#define ISP_3DNR_MEM_CTRL_FT_CUR_LUMA_ADDR      (ISP_3DNR_MEM_CTRL_BASE + 0x0030UL)
#define ISP_3DNR_MEM_CTRL_FT_CUR_CHROMA_ADDR    (ISP_3DNR_MEM_CTRL_BASE + 0x0034UL)
#define ISP_3DNR_MEM_CTRL_FT_CTRL_PITCH         (ISP_3DNR_MEM_CTRL_BASE + 0x0038UL)
#define ISP_3DNR_MEM_CTRL_PARAM8                (ISP_3DNR_MEM_CTRL_BASE + 0x003CUL)
#define ISP_3DNR_MEM_CTRL_PARAM9                (ISP_3DNR_MEM_CTRL_BASE + 0x0040UL)
#define ISP_3DNR_MEM_CTRL_PARAM10               (ISP_3DNR_MEM_CTRL_BASE + 0x0044UL)
#define ISP_3DNR_MEM_CTRL_PARAM11               (ISP_3DNR_MEM_CTRL_BASE + 0x0048UL)
#define ISP_3DNR_MEM_CTRL_PARAM12               (ISP_3DNR_MEM_CTRL_BASE + 0x004CUL)
#define ISP_3DNR_MEM_CTRL_PARAM13               (ISP_3DNR_MEM_CTRL_BASE + 0x0014UL)

#define ISP_3DNR_BLEND_BASE                     (0x2100UL)
#define ISP_3DNR_BLEND_CONTROL0                 (ISP_3DNR_BLEND_BASE + 0x0010UL)
#define ISP_3DNR_BLEND_CFG1                     (ISP_3DNR_BLEND_BASE + 0x0014UL)
#define ISP_3DNR_BLEND_CFG2                     (ISP_3DNR_BLEND_BASE + 0x0018UL)
#define ISP_3DNR_BLEND_CFG3                     (ISP_3DNR_BLEND_BASE + 0x001CUL)
#define ISP_3DNR_BLEND_CFG4                     (ISP_3DNR_BLEND_BASE + 0x0020UL)
#define ISP_3DNR_BLEND_CFG5                     (ISP_3DNR_BLEND_BASE + 0x0024UL)
#define ISP_3DNR_BLEND_CFG6                     (ISP_3DNR_BLEND_BASE + 0x0028UL)
#define ISP_3DNR_BLEND_CFG7                     (ISP_3DNR_BLEND_BASE + 0x002CUL)
#define ISP_3DNR_BLEND_CFG8                     (ISP_3DNR_BLEND_BASE + 0x0030UL)
#define ISP_3DNR_BLEND_CFG9                     (ISP_3DNR_BLEND_BASE + 0x0034UL)
#define ISP_3DNR_BLEND_CFG10                    (ISP_3DNR_BLEND_BASE + 0x0038UL)
#define ISP_3DNR_BLEND_CFG11                    (ISP_3DNR_BLEND_BASE + 0x003CUL)
#define ISP_3DNR_BLEND_CFG12                    (ISP_3DNR_BLEND_BASE + 0x0040UL)
#define ISP_3DNR_BLEND_CFG13                    (ISP_3DNR_BLEND_BASE + 0x0044UL)
#define ISP_3DNR_BLEND_CFG14                    (ISP_3DNR_BLEND_BASE + 0x0048UL)
#define ISP_3DNR_BLEND_CFG15                    (ISP_3DNR_BLEND_BASE + 0x004CUL)
#define ISP_3DNR_BLEND_CFG16                    (ISP_3DNR_BLEND_BASE + 0x0050UL)
#define ISP_3DNR_BLEND_CFG17                    (ISP_3DNR_BLEND_BASE + 0x0054UL)
#define ISP_3DNR_BLEND_CFG18                    (ISP_3DNR_BLEND_BASE + 0x0058UL)
#define ISP_3DNR_BLEND_CFG19                    (ISP_3DNR_BLEND_BASE + 0x005CUL)
#define ISP_3DNR_BLEND_CFG20                    (ISP_3DNR_BLEND_BASE + 0x0060UL)
#define ISP_3DNR_BLEND_CFG21                    (ISP_3DNR_BLEND_BASE + 0x0064UL)
#define ISP_3DNR_BLEND_CFG22                    (ISP_3DNR_BLEND_BASE + 0x0068UL)
#define ISP_3DNR_BLEND_CFG23                    (ISP_3DNR_BLEND_BASE + 0x006CUL)
#define ISP_3DNR_BLEND_CFG24                    (ISP_3DNR_BLEND_BASE + 0x0070UL)

#define ISP_3DNR_STORE_BASE                     (0x2200UL)
#define ISP_3DNR_STORE_PARAM                    (ISP_3DNR_STORE_BASE + 0x0010UL)
#define ISP_3DNR_STORE_SLICE_SIZE               (ISP_3DNR_STORE_BASE + 0x0014UL)
#define ISP_3DNR_STORE_BORDER                   (ISP_3DNR_STORE_BASE + 0x0018UL)
#define ISP_3DNR_STORE_SLICE_Y_ADDR             (ISP_3DNR_STORE_BASE + 0x001CUL)
#define ISP_3DNR_STORE_Y_PITCH                  (ISP_3DNR_STORE_BASE + 0x0020UL)
#define ISP_3DNR_STORE_SLICE_U_ADDR             (ISP_3DNR_STORE_BASE + 0x0024UL)
#define ISP_3DNR_STORE_U_PITCH                  (ISP_3DNR_STORE_BASE + 0x0028UL)
#define ISP_3DNR_STORE_BORDER_1                 (ISP_3DNR_STORE_BASE + 0x002cUL)
#define ISP_3DNR_STORE_V_PITCH                  (ISP_3DNR_STORE_BASE + 0x0030UL)
#define ISP_3DNR_STORE_READ_CTRL                (ISP_3DNR_STORE_BASE + 0x0034UL)
#define ISP_3DNR_STORE_SHADOW_CLR_SEL           (ISP_3DNR_STORE_BASE + 0x0038UL)
#define ISP_3DNR_STORE_SHADOW_CLR               (ISP_3DNR_STORE_BASE + 0x003cUL)

#define ISP_3DNR_CROP_BASE                      (0x2300UL)
#define ISP_3DNR_CROP_PARAM0                    (ISP_3DNR_CROP_BASE + 0x0010UL)
#define ISP_3DNR_CROP_PARAM1                    (ISP_3DNR_CROP_BASE + 0x0014UL)
#define ISP_3DNR_CROP_PARAM2                    (ISP_3DNR_CROP_BASE + 0x0018UL)
#define ISP_3DNR_CROP_PARAM3                    (ISP_3DNR_CROP_BASE + 0x001CUL)

#define ISP_FBC_3DNR_BASE                       (0x2400UL)
#define ISP_FBC_3DNR_PARAM                      (ISP_FBC_3DNR_BASE + 0x0010UL)
#define ISP_FBC_3DNR_SLICE_SIZE                 (ISP_FBC_3DNR_BASE + 0x0014UL)
#define ISP_FBC_3DNR_BORDER                     (ISP_FBC_3DNR_BASE + 0x0018UL)
#define ISP_FBC_3DNR_SLICE_PLOAD_OFFSET_ADDR    (ISP_FBC_3DNR_BASE + 0x001CUL)
#define ISP_FBC_3DNR_SLICE_PLOAD_BASE_ADDR      (ISP_FBC_3DNR_BASE + 0x0020UL)
#define ISP_FBC_3DNR_SLICE_HEADER_BASE_ADDR     (ISP_FBC_3DNR_BASE + 0x0024UL)
#define ISP_FBC_3DNR_TILE_PITCH                 (ISP_FBC_3DNR_BASE + 0x0028UL)
#define ISP_FBC_3DNR_NFULL_LEVEL                (ISP_FBC_3DNR_BASE + 0x002CUL)

#define ISP_FBD_3DNR_BASE                       (0x2500UL)
#define ISP_FBD_3DNR_SEL                        (ISP_FBD_3DNR_BASE + 0x0010UL)
#define ISP_FBD_3DNR_START                      (ISP_FBD_3DNR_BASE + 0x0014UL)
#define ISP_FBD_3DNR_HBLANK_TILE_PITCH          (ISP_FBD_3DNR_BASE + 0x0018UL)
#define ISP_FBD_3DNR_SLICE_SIZE                 (ISP_FBD_3DNR_BASE + 0x001cUL)
#define ISP_FBD_3DNR_PARAM0                     (ISP_FBD_3DNR_BASE + 0x0020UL)
#define ISP_FBD_3DNR_PARAM1                     (ISP_FBD_3DNR_BASE + 0x0024UL)
#define ISP_FBD_3DNR_PARAM2                     (ISP_FBD_3DNR_BASE + 0x0028UL)

#define ISP_3DNR_BWD_BASE                       (0x2700UL)
#define ISP_3DNR_BWD_PARA                       (ISP_3DNR_BWD_BASE + 0x0010UL)

#define ISP_SCALER_CFG                          (0x0010UL)
#define ISP_SCALER_SRC_SIZE                     (0x0014UL)
#define ISP_SCALER_DES_SIZE                     (0x0018UL)
#define ISP_SCALER_TRIM0_START                  (0x001CUL)
#define ISP_SCALER_TRIM0_SIZE                   (0x0020UL)
#define ISP_SCALER_IP                           (0x0024UL)
#define ISP_SCALER_CIP                          (0x0028UL)
#define ISP_SCALER_FACTOR                       (0x002CUL)
#define ISP_SCALER_TRIM1_START                  (0x0030UL)
#define ISP_SCALER_TRIM1_SIZE                   (0x0034UL)
#define ISP_SCALER_VER_IP                       (0x0038UL)
#define ISP_SCALER_VER_CIP                      (0x003CUL)
#define ISP_SCALER_FACTOR_VER                   (0x0040UL)
#define ISP_SCALER_DEBUG                        (0x0044UL)
#define ISP_SCALER_HBLANK                       (0x0048UL)
#define ISP_SCALER_FRAME_CNT_CLR                (0x004CUL)
#define ISP_SCALER_RES                          (0x0050UL)

#define ISP_SCALER_PRE_CAP_BASE                 (0x5000UL)
#define ISP_CAP_SCALER_CFG                      (ISP_SCALER_PRE_CAP_BASE + 0x0010UL)
#define ISP_CAP_SCALER_SRC_SIZE                 (ISP_SCALER_PRE_CAP_BASE + 0x0014UL)
#define ISP_CAP_SCALER_DES_SIZE                 (ISP_SCALER_PRE_CAP_BASE + 0x0018UL)
#define ISP_CAP_SCALER_TRIM0_START              (ISP_SCALER_PRE_CAP_BASE + 0x001CUL)
#define ISP_CAP_SCALER_TRIM0_SIZE               (ISP_SCALER_PRE_CAP_BASE + 0x0020UL)
#define ISP_CAP_SCALER_IP                       (ISP_SCALER_PRE_CAP_BASE + 0x0024UL)
#define ISP_CAP_SCALER_CIP                      (ISP_SCALER_PRE_CAP_BASE + 0x0028UL)
#define ISP_CAP_SCALER_FACTOR                   (ISP_SCALER_PRE_CAP_BASE + 0x002CUL)
#define ISP_CAP_SCALER_TRIM1_START              (ISP_SCALER_PRE_CAP_BASE + 0x0030UL)
#define ISP_CAP_SCALER_TRIM1_SIZE               (ISP_SCALER_PRE_CAP_BASE + 0x0034UL)
#define ISP_CAP_SCALER_IP_VER                   (ISP_SCALER_PRE_CAP_BASE + 0x0038UL)
#define ISP_CAP_SCALER_CIP_VER                  (ISP_SCALER_PRE_CAP_BASE + 0x003CUL)
#define ISP_CAP_SCALER_FACTOR_VER               (ISP_SCALER_PRE_CAP_BASE + 0x0040UL)
#define ISP_CAP_SCALER_DEBUG                    (ISP_SCALER_PRE_CAP_BASE + 0x0044UL)
#define ISP_CAP_SCALER_HBLANK                   (ISP_SCALER_PRE_CAP_BASE + 0x0048UL)
#define ISP_CAP_SCALER_FRAME_CNT_CLR            (ISP_SCALER_PRE_CAP_BASE + 0x004CUL)
#define ISP_CAP_SCALER_RES                      (ISP_SCALER_PRE_CAP_BASE + 0x0050UL)
#define ISP_CAP_SCALER_BWD_PARA                 (ISP_SCALER_PRE_CAP_BASE + 0x0054UL)
#define ISP_CAP_SCALER_DBG_ESL                  (ISP_SCALER_PRE_CAP_BASE + 0x0058UL)

#define ISP_SCALER_VID_BASE                     (0x6000UL)
#define ISP_RECORD_SCALER_CFG                   (ISP_SCALER_VID_BASE + 0x0010UL)
#define ISP_RECORD_SCALER_SRC_SIZE              (ISP_SCALER_VID_BASE + 0x0014UL)
#define ISP_RECORD_SCALER_DES_SIZE              (ISP_SCALER_VID_BASE + 0x0018UL)
#define ISP_RECORD_SCALER_TRIM0_START           (ISP_SCALER_VID_BASE + 0x001CUL)
#define ISP_RECORD_SCALER_TRIM0_SIZE            (ISP_SCALER_VID_BASE + 0x0020UL)
#define ISP_RECORD_SCALER_IP                    (ISP_SCALER_VID_BASE + 0x0024UL)
#define ISP_RECORD_SCALER_CIP                   (ISP_SCALER_VID_BASE + 0x0028UL)
#define ISP_RECORD_SCALER_FACTOR                (ISP_SCALER_VID_BASE + 0x002CUL)
#define ISP_RECORD_SCALER_TRIM1_START           (ISP_SCALER_VID_BASE + 0x0030UL)
#define ISP_RECORD_SCALER_TRIM1_SIZE            (ISP_SCALER_VID_BASE + 0x0034UL)
#define ISP_RECORD_SCALER_IP_VER                (ISP_SCALER_VID_BASE + 0x0038UL)
#define ISP_RECORD_SCALER_CIP_VER               (ISP_SCALER_VID_BASE + 0x003CUL)
#define ISP_RECORD_SCALER_FACTOR_VER            (ISP_SCALER_VID_BASE + 0x0040UL)
#define ISP_RECORD_SCALER_DEBUG                 (ISP_SCALER_VID_BASE + 0x0044UL)
#define ISP_RECORD_SCALER_HBLANK                (ISP_SCALER_VID_BASE + 0x0048UL)
#define ISP_RECORD_SCALER_FRAME_CNT_CLR         (ISP_SCALER_VID_BASE + 0x004CUL)
#define ISP_RECORD_SCALER_RES                   (ISP_SCALER_VID_BASE + 0x0050UL)
#define ISP_RECORD_SCALER_SHRINK_CFG_UV         (ISP_SCALER_VID_BASE + 0x0054UL)
#define ISP_RECORD_SCALER_SHRINK_CFG_Y          (ISP_SCALER_VID_BASE + 0x0058UL)
#define ISP_RECORD_SCALER_EFFECT_CFG_UV         (ISP_SCALER_VID_BASE + 0x005CUL)
#define ISP_RECORD_SCALER_EFFECT_CFG_Y          (ISP_SCALER_VID_BASE + 0x0060UL)
#define ISP_RECORD_SCALER_REGULAR_CFG           (ISP_SCALER_VID_BASE + 0x0064UL)
#define ISP_RECORD_SCALER_BWD_PARA              (ISP_SCALER_VID_BASE + 0x0068UL)
#define ISP_RECORD_SCALER_DBG_ESL               (ISP_SCALER_VID_BASE + 0x006CUL)

#define ISP_SCALER_THUMB_BASE                   (0x7000UL)
#define ISP_THMB_SCALER_CFG                     (ISP_SCALER_THUMB_BASE + 0x0010UL)
#define ISP_THMB_SCALER_BEFORE_TRIM_SIZE        (ISP_SCALER_THUMB_BASE + 0x0014UL)
#define ISP_THMB_SCALER_Y_SLICE_SRC_SIZE        (ISP_SCALER_THUMB_BASE + 0x0018UL)
#define ISP_THMB_SCALER_Y_DES_SIZE              (ISP_SCALER_THUMB_BASE + 0x001CUL)
#define ISP_THMB_SCALER_Y_TRIM0_START           (ISP_SCALER_THUMB_BASE + 0x0020UL)
#define ISP_THMB_SCALER_Y_TRIM0_SIZE            (ISP_SCALER_THUMB_BASE + 0x0024UL)
#define ISP_THMB_SCALER_Y_INIT_PHASE            (ISP_SCALER_THUMB_BASE + 0x0028UL)
#define ISP_THMB_SCALER_Y_FACTOR_HOR            (ISP_SCALER_THUMB_BASE + 0x002CUL)
#define ISP_THMB_SCALER_Y_FACTOR_VER            (ISP_SCALER_THUMB_BASE + 0x0030UL)
#define ISP_THMB_SCALER_UV_SLICE_SRC_SIZE       (ISP_SCALER_THUMB_BASE + 0x0034UL)
#define ISP_THMB_SCALER_UV_DES_SIZE             (ISP_SCALER_THUMB_BASE + 0x0038UL)
#define ISP_THMB_SCALER_UV_TRIM0_START          (ISP_SCALER_THUMB_BASE + 0x003CUL)
#define ISP_THMB_SCALER_UV_TRIM0_SIZE           (ISP_SCALER_THUMB_BASE + 0x0040UL)
#define ISP_THMB_SCALER_UV_INIT_PHASE           (ISP_SCALER_THUMB_BASE + 0x0044UL)
#define ISP_THMB_SCALER_UV_FACTOR_HOR           (ISP_SCALER_THUMB_BASE + 0x0048UL)
#define ISP_THMB_SCALER_UV_FACTOR_VER           (ISP_SCALER_THUMB_BASE + 0x004CUL)
#define ISP_THMB_SCALER_SHRINK_CFG_UV           (ISP_SCALER_THUMB_BASE + 0x0050UL)
#define ISP_THMB_SCALER_SHRINK_CFG_Y            (ISP_SCALER_THUMB_BASE + 0x0054UL)
#define ISP_THMB_SCALER_EFFECT_CFG_UV           (ISP_SCALER_THUMB_BASE + 0x0058UL)
#define ISP_THMB_SCALER_EFFECT_CFG_Y            (ISP_SCALER_THUMB_BASE + 0x005CUL)
#define ISP_THMB_SCALER_REGULAR_CFG             (ISP_SCALER_THUMB_BASE + 0x0060UL)
#define ISP_THMB_SCALER_SCL_DEBUG               (ISP_SCALER_THUMB_BASE + 0x0064UL)
#define ISP_THMB_SCALER_FRAME_CNT_CLR           (ISP_SCALER_THUMB_BASE + 0x0068UL)
#define ISP_THMB_SCL_BWD_PARA                   (ISP_SCALER_THUMB_BASE + 0x006CUL)

#define ISP_YUV_CAP_SCL_COEF_ADDR1              (0x5100UL)
#define ISP_YUV_CAP_SCL_COEF1_ADDR1             (0x5500UL)
#define ISP_YUV_CAP_SCL_COEF2_ADDR1             (0x5600UL)
#define ISP_YUV_CAP_SCL_COEF3_ADDR1             (0x5700UL)

#define ISP_CAP_PATH_VER_CORF_Y_BUF0_CH0        (0x1d8f0UL)
#define ISP_CAP_PATH_VER_CORF_UV_BUF0_CH0       (0x1f000UL)

#define ISP_YUV_VID_SCL_COEF_ADDR2              (0x6100UL)
#define ISP_YUV_VID_SCL_COEF1_ADDR2             (0x6500UL)
#define ISP_YUV_VID_SCL_COEF2_ADDR2             (0x6600UL)
#define ISP_YUV_VID_SCL_COEF3_ADDR2             (0x6700UL)

#define ISP_VID_PATH_VER_CORF_Y_BUF0_CH0        (0x21400UL)
#define ISP_VID_PATH_VER_CORF_UV_BUF0_CH0       (0x21c00UL)

#define ISP_SCL_PATH_HOR_CORF_Y                 (0x10UL)
#define ISP_SCL_PATH_HOR_CORF_UV                (0x90UL)

#define ISP_STORE_PRE_CAP_BASE                  (0x5200UL)
#define ISP_STORE_VID_BASE                      (0x6200UL)
#define ISP_STORE_THUMB_BASE                    (0x7100UL)
#define PYR_DEC_STORE_BASE                      (0x8400UL)
#define PYR_DCT_STORE_BASE                      (0x8600UL)
#define PYR_REC_STORE_BASE                      (0x9600UL)

#define ISP_STORE_PARAM                         (0x0010UL)
#define ISP_STORE_SLICE_SIZE                    (0x0014UL)
#define ISP_STORE_BORDER                        (0x0018UL)
#define ISP_STORE_SLICE_Y_ADDR                  (0x001CUL)
#define ISP_STORE_Y_PITCH                       (0x0020UL)
#define ISP_STORE_SLICE_U_ADDR                  (0x0024UL)
#define ISP_STORE_U_PITCH                       (0x0028UL)
#define ISP_STORE_BORDER_1                      (0x002CUL)
#define ISP_STORE_V_PITCH                       (0x0030UL)
#define ISP_STORE_READ_CTRL                     (0x0034UL)
#define ISP_STORE_SHADOW_CLR_SEL                (0x0038UL)
#define ISP_STORE_SHADOW_CLR                    (0x003CUL)

#define ISP_CAP_FBC_STORE_BASE                  (0x5300UL)
#define ISP_VID_FBC_STORE_BASE                  (0x6300UL)

#define ISP_FBC_STORE_PARAM                     (0x0010UL)
#define ISP_FBC_STORE_SLICE_SIZE                (0x0014UL)
#define ISP_FBC_STORE_BORDER                    (0x0018UL)
#define ISP_FBC_STORE_SLICE_PAYLOAD_OFFSET_ADDR (0x001CUL)
#define ISP_FBC_STORE_SLICE_PAYLOAD_BASE_ADDR   (0x0020UL)
#define ISP_FBC_STORE_SLICE_HEADER_BASE_ADDR    (0x0024UL)
#define ISP_FBC_STORE_TILE_PITCH                (0x0028UL)
#define ISP_FBC_STORE_NFULL_LEVEL               (0x002CUL)

#define ISP_YUV_NF_BASE                         (0x5400UL)
#define ISP_YUV_NF_CTRL                         (ISP_YUV_NF_BASE + 0x0010UL)
#define ISP_YUV_NF_SEED0                        (ISP_YUV_NF_BASE + 0x0014UL)
#define ISP_YUV_NF_SEED1                        (ISP_YUV_NF_BASE + 0x0018UL)
#define ISP_YUV_NF_SEED2                        (ISP_YUV_NF_BASE + 0x001CUL)
#define ISP_YUV_NF_SEED3                        (ISP_YUV_NF_BASE + 0x0020UL)
#define ISP_YUV_NF_TB4                          (ISP_YUV_NF_BASE + 0x0024UL)
#define ISP_YUV_NF_SF                           (ISP_YUV_NF_BASE + 0x0028UL)
#define ISP_YUV_NF_THR                          (ISP_YUV_NF_BASE + 0x002CUL)
#define ISP_YUV_NF_CV_T12                       (ISP_YUV_NF_BASE + 0x0030UL)
#define ISP_YUV_NF_CV_R                         (ISP_YUV_NF_BASE + 0x0034UL)
#define ISP_YUV_NF_CLIP                         (ISP_YUV_NF_BASE + 0x0038UL)
#define ISP_YUV_NF_SEED_INIT                    (ISP_YUV_NF_BASE + 0x003CUL)
#define ISP_YUV_NF_CV_T34                       (ISP_YUV_NF_BASE + 0x0040UL)

#define ISP_DECOMPOSE_OFFLINE_BASE              (0x8300UL)
#define ISP_DEC_OFFLINE_PARAM                   (ISP_DECOMPOSE_OFFLINE_BASE + 0x0010UL)
#define ISP_DEC_OFFLINE_PARAM1                  (ISP_DECOMPOSE_OFFLINE_BASE + 0x0014UL)

#define ISP_DCT_YNR_BASE                        (0x8500UL)
#define ISP_YNR_DCT_PARAM                       (ISP_DCT_YNR_BASE + 0x0010UL)
#define ISP_YNR_DCT_PARAM1                      (ISP_DCT_YNR_BASE + 0x0014UL)
#define ISP_YNR_DCT_PARAM2                      (ISP_DCT_YNR_BASE + 0x0018UL)
#define ISP_YNR_DCT_PARAM3                      (ISP_DCT_YNR_BASE + 0x001CUL)
#define ISP_YNR_DCT_PARAM4                      (ISP_DCT_YNR_BASE + 0x0020UL)
#define ISP_YNR_DCT_PARAM5                      (ISP_DCT_YNR_BASE + 0x0024UL)
#define ISP_YNR_DCT_PARAM6                      (ISP_DCT_YNR_BASE + 0x0028UL)
#define ISP_YNR_DCT_PARAM7                      (ISP_DCT_YNR_BASE + 0x002CUL)
#define ISP_YNR_DCT_PARAM8                      (ISP_DCT_YNR_BASE + 0x0030UL)
#define ISP_YNR_DCT_PARAM9                      (ISP_DCT_YNR_BASE + 0x0034UL)
#define ISP_YNR_DCT_PARAM10                     (ISP_DCT_YNR_BASE + 0x0038UL)
#define ISP_YNR_DCT_PARAM11                     (ISP_DCT_YNR_BASE + 0x003CUL)
#define ISP_YNR_DCT_PARAM12                     (ISP_DCT_YNR_BASE + 0x0040UL)
#define ISP_YNR_DCT_PARAM13                     (ISP_DCT_YNR_BASE + 0x0044UL)
#define ISP_YNR_DCT_PARAM14                     (ISP_DCT_YNR_BASE + 0x0048UL)
#define ISP_YNR_DCT_PARAM15                     (ISP_DCT_YNR_BASE + 0x004CUL)

#define ISP_YUV_RECONSTRUCT_BASE                (0x9500UL)
#define ISP_REC_PARAM                           (ISP_YUV_RECONSTRUCT_BASE + 0x0010UL)
#define ISP_REC_PARAM1                          (ISP_YUV_RECONSTRUCT_BASE + 0x0014UL)
#define ISP_REC_PARAM2                          (ISP_YUV_RECONSTRUCT_BASE + 0x0018UL)
#define ISP_REC_PARAM3                          (ISP_YUV_RECONSTRUCT_BASE + 0x001CUL)
#define ISP_REC_PARAM4                          (ISP_YUV_RECONSTRUCT_BASE + 0x0020UL)
#define ISP_REC_PARAM5                          (ISP_YUV_RECONSTRUCT_BASE + 0x0024UL)
#define ISP_REC_PARAM6                          (ISP_YUV_RECONSTRUCT_BASE + 0x0028UL)
#define ISP_REC_PARAM7                          (ISP_YUV_RECONSTRUCT_BASE + 0x002CUL)
#define ISP_REC_PARAM8                          (ISP_YUV_RECONSTRUCT_BASE + 0x0030UL)
#define ISP_REC_PARAM9                          (ISP_YUV_RECONSTRUCT_BASE + 0x0034UL)

#define ISP_YUV_REC_CNR_BASE                    (0x9700UL)
#define ISP_YUV_REC_CNR_CONTRL0                 (ISP_YUV_REC_CNR_BASE + 0x0010UL)
#define ISP_YUV_REC_CNR_CONTRL1                 (ISP_YUV_REC_CNR_BASE + 0x0014UL)
#define ISP_YUV_REC_CNR_CFG0                    (ISP_YUV_REC_CNR_BASE + 0x0018UL)
#define ISP_YUV_REC_CNR_CFG1                    (ISP_YUV_REC_CNR_BASE + 0x001CUL)
#define ISP_YUV_REC_CNR_CFG2                    (ISP_YUV_REC_CNR_BASE + 0x0020UL)
#define ISP_YUV_REC_CNR_RESERVED1               (ISP_YUV_REC_CNR_BASE + 0x0024UL)
#define ISP_YUV_REC_CNR_RESERVED2               (ISP_YUV_REC_CNR_BASE + 0x0028UL)
#define ISP_YUV_REC_CNR_RESERVED3               (ISP_YUV_REC_CNR_BASE + 0x002CUL)
#define ISP_YUV_REC_CNR_RESERVED4               (ISP_YUV_REC_CNR_BASE + 0x0030UL)
#define ISP_YUV_REC_CNR_RESERVED5               (ISP_YUV_REC_CNR_BASE + 0x0034UL)
#define ISP_YUV_REC_CNR_RESERVED6               (ISP_YUV_REC_CNR_BASE + 0x0038UL)
#define ISP_YUV_REC_CNR_RESERVED7               (ISP_YUV_REC_CNR_BASE + 0x003CUL)
#define ISP_YUV_REC_CNR_Y_L0_WHT0               (ISP_YUV_REC_CNR_BASE + 0x0040UL)
#define ISP_YUV_REC_CNR_Y_L0_WHT1               (ISP_YUV_REC_CNR_BASE + 0x0044UL)
#define ISP_YUV_REC_CNR_Y_L0_WHT2               (ISP_YUV_REC_CNR_BASE + 0x0048UL)
#define ISP_YUV_REC_CNR_Y_L0_WHT3               (ISP_YUV_REC_CNR_BASE + 0x004CUL)
#define ISP_YUV_REC_CNR_Y_L0_WHT4               (ISP_YUV_REC_CNR_BASE + 0x0050UL)
#define ISP_YUV_REC_CNR_Y_L0_WHT5               (ISP_YUV_REC_CNR_BASE + 0x0054UL)
#define ISP_YUV_REC_CNR_Y_L0_WHT6               (ISP_YUV_REC_CNR_BASE + 0x0058UL)
#define ISP_YUV_REC_CNR_Y_L0_WHT7               (ISP_YUV_REC_CNR_BASE + 0x005CUL)
#define ISP_YUV_REC_CNR_Y_L0_WHT8               (ISP_YUV_REC_CNR_BASE + 0x0060UL)
#define ISP_YUV_REC_CNR_Y_L0_WHT9               (ISP_YUV_REC_CNR_BASE + 0x0064UL)
#define ISP_YUV_REC_CNR_Y_L0_WHT10              (ISP_YUV_REC_CNR_BASE + 0x0068UL)
#define ISP_YUV_REC_CNR_Y_L0_WHT11              (ISP_YUV_REC_CNR_BASE + 0x006CUL)
#define ISP_YUV_REC_CNR_Y_L0_WHT12              (ISP_YUV_REC_CNR_BASE + 0x0070UL)
#define ISP_YUV_REC_CNR_Y_L0_WHT13              (ISP_YUV_REC_CNR_BASE + 0x0074UL)
#define ISP_YUV_REC_CNR_Y_L0_WHT14              (ISP_YUV_REC_CNR_BASE + 0x0078UL)
#define ISP_YUV_REC_CNR_Y_L0_WHT15              (ISP_YUV_REC_CNR_BASE + 0x007CUL)
#define ISP_YUV_REC_CNR_Y_L0_WHT16              (ISP_YUV_REC_CNR_BASE + 0x0080UL)
#define ISP_YUV_REC_CNR_Y_L0_WHT17              (ISP_YUV_REC_CNR_BASE + 0x0084UL)
#define ISP_YUV_REC_CNR_Y_L1_WHT0               (ISP_YUV_REC_CNR_BASE + 0x0088UL)
#define ISP_YUV_REC_CNR_Y_L1_WHT1               (ISP_YUV_REC_CNR_BASE + 0x008CUL)
#define ISP_YUV_REC_CNR_Y_L1_WHT2               (ISP_YUV_REC_CNR_BASE + 0x0090UL)
#define ISP_YUV_REC_CNR_Y_L1_WHT3               (ISP_YUV_REC_CNR_BASE + 0x0094UL)
#define ISP_YUV_REC_CNR_Y_L1_WHT4               (ISP_YUV_REC_CNR_BASE + 0x0098UL)
#define ISP_YUV_REC_CNR_Y_L1_WHT5               (ISP_YUV_REC_CNR_BASE + 0x009CUL)
#define ISP_YUV_REC_CNR_Y_L1_WHT6               (ISP_YUV_REC_CNR_BASE + 0x00A0UL)
#define ISP_YUV_REC_CNR_Y_L1_WHT7               (ISP_YUV_REC_CNR_BASE + 0x00A4UL)
#define ISP_YUV_REC_CNR_Y_L1_WHT8               (ISP_YUV_REC_CNR_BASE + 0x00A8UL)
#define ISP_YUV_REC_CNR_Y_L1_WHT9               (ISP_YUV_REC_CNR_BASE + 0x00ACUL)
#define ISP_YUV_REC_CNR_Y_L1_WHT10              (ISP_YUV_REC_CNR_BASE + 0x00B0UL)
#define ISP_YUV_REC_CNR_Y_L1_WHT11              (ISP_YUV_REC_CNR_BASE + 0x00B4UL)
#define ISP_YUV_REC_CNR_Y_L1_WHT12              (ISP_YUV_REC_CNR_BASE + 0x00B8UL)
#define ISP_YUV_REC_CNR_Y_L1_WHT13              (ISP_YUV_REC_CNR_BASE + 0x00BCUL)
#define ISP_YUV_REC_CNR_Y_L1_WHT14              (ISP_YUV_REC_CNR_BASE + 0x00C0UL)
#define ISP_YUV_REC_CNR_Y_L1_WHT15              (ISP_YUV_REC_CNR_BASE + 0x00C4UL)
#define ISP_YUV_REC_CNR_Y_L1_WHT16              (ISP_YUV_REC_CNR_BASE + 0x00C8UL)
#define ISP_YUV_REC_CNR_Y_L1_WHT17              (ISP_YUV_REC_CNR_BASE + 0x00CCUL)
#define ISP_YUV_REC_CNR_Y_L2_WHT0               (ISP_YUV_REC_CNR_BASE + 0x00D0UL)
#define ISP_YUV_REC_CNR_Y_L2_WHT1               (ISP_YUV_REC_CNR_BASE + 0x00D4UL)
#define ISP_YUV_REC_CNR_Y_L2_WHT2               (ISP_YUV_REC_CNR_BASE + 0x00D8UL)
#define ISP_YUV_REC_CNR_Y_L2_WHT3               (ISP_YUV_REC_CNR_BASE + 0x00DCUL)
#define ISP_YUV_REC_CNR_Y_L2_WHT4               (ISP_YUV_REC_CNR_BASE + 0x00E0UL)
#define ISP_YUV_REC_CNR_Y_L2_WHT5               (ISP_YUV_REC_CNR_BASE + 0x00E4UL)
#define ISP_YUV_REC_CNR_Y_L2_WHT6               (ISP_YUV_REC_CNR_BASE + 0x00E8UL)
#define ISP_YUV_REC_CNR_Y_L2_WHT7               (ISP_YUV_REC_CNR_BASE + 0x00ECUL)
#define ISP_YUV_REC_CNR_Y_L2_WHT8               (ISP_YUV_REC_CNR_BASE + 0x00F0UL)
#define ISP_YUV_REC_CNR_Y_L2_WHT9               (ISP_YUV_REC_CNR_BASE + 0x00F4UL)
#define ISP_YUV_REC_CNR_Y_L2_WHT10              (ISP_YUV_REC_CNR_BASE + 0x00F8UL)
#define ISP_YUV_REC_CNR_Y_L2_WHT11              (ISP_YUV_REC_CNR_BASE + 0x00FCUL)
#define ISP_YUV_REC_CNR_Y_L2_WHT12              (ISP_YUV_REC_CNR_BASE + 0x0100UL)
#define ISP_YUV_REC_CNR_Y_L2_WHT13              (ISP_YUV_REC_CNR_BASE + 0x0104UL)
#define ISP_YUV_REC_CNR_Y_L2_WHT14              (ISP_YUV_REC_CNR_BASE + 0x0108UL)
#define ISP_YUV_REC_CNR_Y_L2_WHT15              (ISP_YUV_REC_CNR_BASE + 0x010CUL)
#define ISP_YUV_REC_CNR_Y_L2_WHT16              (ISP_YUV_REC_CNR_BASE + 0x0110UL)
#define ISP_YUV_REC_CNR_Y_L2_WHT17              (ISP_YUV_REC_CNR_BASE + 0x0114UL)
#define ISP_YUV_REC_CNR_UV_L0_WHT0              (ISP_YUV_REC_CNR_BASE + 0x0118UL)
#define ISP_YUV_REC_CNR_UV_L0_WHT1              (ISP_YUV_REC_CNR_BASE + 0x011CUL)
#define ISP_YUV_REC_CNR_UV_L0_WHT2              (ISP_YUV_REC_CNR_BASE + 0x0120UL)
#define ISP_YUV_REC_CNR_UV_L0_WHT3              (ISP_YUV_REC_CNR_BASE + 0x0124UL)
#define ISP_YUV_REC_CNR_UV_L0_WHT4              (ISP_YUV_REC_CNR_BASE + 0x0128UL)
#define ISP_YUV_REC_CNR_UV_L0_WHT5              (ISP_YUV_REC_CNR_BASE + 0x012CUL)
#define ISP_YUV_REC_CNR_UV_L0_WHT6              (ISP_YUV_REC_CNR_BASE + 0x0130UL)
#define ISP_YUV_REC_CNR_UV_L0_WHT7              (ISP_YUV_REC_CNR_BASE + 0x0134UL)
#define ISP_YUV_REC_CNR_UV_L0_WHT8              (ISP_YUV_REC_CNR_BASE + 0x0138UL)
#define ISP_YUV_REC_CNR_UV_L0_WHT9              (ISP_YUV_REC_CNR_BASE + 0x013CUL)
#define ISP_YUV_REC_CNR_UV_L0_WHT10             (ISP_YUV_REC_CNR_BASE + 0x0140UL)
#define ISP_YUV_REC_CNR_UV_L0_WHT11             (ISP_YUV_REC_CNR_BASE + 0x0144UL)
#define ISP_YUV_REC_CNR_UV_L0_WHT12             (ISP_YUV_REC_CNR_BASE + 0x0148UL)
#define ISP_YUV_REC_CNR_UV_L0_WHT13             (ISP_YUV_REC_CNR_BASE + 0x014CUL)
#define ISP_YUV_REC_CNR_UV_L0_WHT14             (ISP_YUV_REC_CNR_BASE + 0x0150UL)
#define ISP_YUV_REC_CNR_UV_L0_WHT15             (ISP_YUV_REC_CNR_BASE + 0x0154UL)
#define ISP_YUV_REC_CNR_UV_L0_WHT16             (ISP_YUV_REC_CNR_BASE + 0x0158UL)
#define ISP_YUV_REC_CNR_UV_L0_WHT17             (ISP_YUV_REC_CNR_BASE + 0x015CUL)
#define ISP_YUV_REC_CNR_UV_L1_WHT0              (ISP_YUV_REC_CNR_BASE + 0x0160UL)
#define ISP_YUV_REC_CNR_UV_L1_WHT1              (ISP_YUV_REC_CNR_BASE + 0x0164UL)
#define ISP_YUV_REC_CNR_UV_L1_WHT2              (ISP_YUV_REC_CNR_BASE + 0x0168UL)
#define ISP_YUV_REC_CNR_UV_L1_WHT3              (ISP_YUV_REC_CNR_BASE + 0x016CUL)
#define ISP_YUV_REC_CNR_UV_L1_WHT4              (ISP_YUV_REC_CNR_BASE + 0x0170UL)
#define ISP_YUV_REC_CNR_UV_L1_WHT5              (ISP_YUV_REC_CNR_BASE + 0x0174UL)
#define ISP_YUV_REC_CNR_UV_L1_WHT6              (ISP_YUV_REC_CNR_BASE + 0x0178UL)
#define ISP_YUV_REC_CNR_UV_L1_WHT7              (ISP_YUV_REC_CNR_BASE + 0x017CUL)
#define ISP_YUV_REC_CNR_UV_L1_WHT8              (ISP_YUV_REC_CNR_BASE + 0x0180UL)
#define ISP_YUV_REC_CNR_UV_L1_WHT9              (ISP_YUV_REC_CNR_BASE + 0x0184UL)
#define ISP_YUV_REC_CNR_UV_L1_WHT10             (ISP_YUV_REC_CNR_BASE + 0x0188UL)
#define ISP_YUV_REC_CNR_UV_L1_WHT11             (ISP_YUV_REC_CNR_BASE + 0x018CUL)
#define ISP_YUV_REC_CNR_UV_L1_WHT12             (ISP_YUV_REC_CNR_BASE + 0x0190UL)
#define ISP_YUV_REC_CNR_UV_L1_WHT13             (ISP_YUV_REC_CNR_BASE + 0x0194UL)
#define ISP_YUV_REC_CNR_UV_L1_WHT14             (ISP_YUV_REC_CNR_BASE + 0x0198UL)
#define ISP_YUV_REC_CNR_UV_L1_WHT15             (ISP_YUV_REC_CNR_BASE + 0x019CUL)
#define ISP_YUV_REC_CNR_UV_L1_WHT16             (ISP_YUV_REC_CNR_BASE + 0x01A0UL)
#define ISP_YUV_REC_CNR_UV_L1_WHT17             (ISP_YUV_REC_CNR_BASE + 0x01A4UL)
#define ISP_YUV_REC_CNR_UV_L2_WHT0              (ISP_YUV_REC_CNR_BASE + 0x01A8UL)
#define ISP_YUV_REC_CNR_UV_L2_WHT1              (ISP_YUV_REC_CNR_BASE + 0x01ACUL)
#define ISP_YUV_REC_CNR_UV_L2_WHT2              (ISP_YUV_REC_CNR_BASE + 0x01B0UL)
#define ISP_YUV_REC_CNR_UV_L2_WHT3              (ISP_YUV_REC_CNR_BASE + 0x01B4UL)
#define ISP_YUV_REC_CNR_UV_L2_WHT4              (ISP_YUV_REC_CNR_BASE + 0x01B8UL)
#define ISP_YUV_REC_CNR_UV_L2_WHT5              (ISP_YUV_REC_CNR_BASE + 0x01BCUL)
#define ISP_YUV_REC_CNR_UV_L2_WHT6              (ISP_YUV_REC_CNR_BASE + 0x01C0UL)
#define ISP_YUV_REC_CNR_UV_L2_WHT7              (ISP_YUV_REC_CNR_BASE + 0x01C4UL)
#define ISP_YUV_REC_CNR_UV_L2_WHT8              (ISP_YUV_REC_CNR_BASE + 0x01C8UL)
#define ISP_YUV_REC_CNR_UV_L2_WHT9              (ISP_YUV_REC_CNR_BASE + 0x01CCUL)
#define ISP_YUV_REC_CNR_UV_L2_WHT10             (ISP_YUV_REC_CNR_BASE + 0x01D0UL)
#define ISP_YUV_REC_CNR_UV_L2_WHT11             (ISP_YUV_REC_CNR_BASE + 0x01D4UL)
#define ISP_YUV_REC_CNR_UV_L2_WHT12             (ISP_YUV_REC_CNR_BASE + 0x01D8UL)
#define ISP_YUV_REC_CNR_UV_L2_WHT13             (ISP_YUV_REC_CNR_BASE + 0x01DCUL)
#define ISP_YUV_REC_CNR_UV_L2_WHT14             (ISP_YUV_REC_CNR_BASE + 0x01E0UL)
#define ISP_YUV_REC_CNR_UV_L2_WHT15             (ISP_YUV_REC_CNR_BASE + 0x01E4UL)
#define ISP_YUV_REC_CNR_UV_L2_WHT16             (ISP_YUV_REC_CNR_BASE + 0x01E8UL)
#define ISP_YUV_REC_CNR_UV_L2_WHT17             (ISP_YUV_REC_CNR_BASE + 0x01ECUL)

#define ISP_YUV_REC_YNR_BASE                    (0x9A00UL)
#define ISP_YUV_REC_YNR_CONTRL0                 (ISP_YUV_REC_YNR_BASE + 0x0010UL)
#define ISP_YUV_REC_YNR_CFG0                    (ISP_YUV_REC_YNR_BASE + 0x0014UL)
#define ISP_YUV_REC_YNR_CFG1                    (ISP_YUV_REC_YNR_BASE + 0x0018UL)
#define ISP_YUV_REC_YNR_L1_CFG0                 (ISP_YUV_REC_YNR_BASE + 0x001CUL)
#define ISP_YUV_REC_YNR_L1_CFG1                 (ISP_YUV_REC_YNR_BASE + 0x0020UL)
#define ISP_YUV_REC_YNR_L1_CFG2                 (ISP_YUV_REC_YNR_BASE + 0x0024UL)
#define ISP_YUV_REC_YNR_L1_CFG3                 (ISP_YUV_REC_YNR_BASE + 0x0028UL)
#define ISP_YUV_REC_YNR_L1_CFG4                 (ISP_YUV_REC_YNR_BASE + 0x002CUL)
#define ISP_YUV_REC_YNR_L1_CFG5                 (ISP_YUV_REC_YNR_BASE + 0x0030UL)
#define ISP_YUV_REC_YNR_L2_CFG0                 (ISP_YUV_REC_YNR_BASE + 0x0034UL)
#define ISP_YUV_REC_YNR_L2_CFG1                 (ISP_YUV_REC_YNR_BASE + 0x0038UL)
#define ISP_YUV_REC_YNR_L2_CFG2                 (ISP_YUV_REC_YNR_BASE + 0x003CUL)
#define ISP_YUV_REC_YNR_L2_CFG3                 (ISP_YUV_REC_YNR_BASE + 0x0040UL)
#define ISP_YUV_REC_YNR_L2_CFG4                 (ISP_YUV_REC_YNR_BASE + 0x0044UL)
#define ISP_YUV_REC_YNR_L2_CFG5                 (ISP_YUV_REC_YNR_BASE + 0x0048UL)
#define ISP_YUV_REC_YNR_L3_CFG0                 (ISP_YUV_REC_YNR_BASE + 0x004CUL)
#define ISP_YUV_REC_YNR_L3_CFG1                 (ISP_YUV_REC_YNR_BASE + 0x0050UL)
#define ISP_YUV_REC_YNR_L3_CFG2                 (ISP_YUV_REC_YNR_BASE + 0x0054UL)
#define ISP_YUV_REC_YNR_L3_CFG3                 (ISP_YUV_REC_YNR_BASE + 0x0058UL)
#define ISP_YUV_REC_YNR_L3_CFG4                 (ISP_YUV_REC_YNR_BASE + 0x005CUL)
#define ISP_YUV_REC_YNR_L3_CFG5                 (ISP_YUV_REC_YNR_BASE + 0x0060UL)
#define ISP_YUV_REC_YNR_L4_CFG0                 (ISP_YUV_REC_YNR_BASE + 0x0064UL)
#define ISP_YUV_REC_YNR_L4_CFG1                 (ISP_YUV_REC_YNR_BASE + 0x0068UL)
#define ISP_YUV_REC_YNR_L4_CFG2                 (ISP_YUV_REC_YNR_BASE + 0x006CUL)
#define ISP_YUV_REC_YNR_L4_CFG3                 (ISP_YUV_REC_YNR_BASE + 0x0070UL)
#define ISP_YUV_REC_YNR_L4_CFG4                 (ISP_YUV_REC_YNR_BASE + 0x0074UL)
#define ISP_YUV_REC_YNR_L4_CFG5                 (ISP_YUV_REC_YNR_BASE + 0x0078UL)
#define ISP_YUV_REC_YNR_L5_CFG0                 (ISP_YUV_REC_YNR_BASE + 0x007CUL)
#define ISP_YUV_REC_YNR_L5_CFG1                 (ISP_YUV_REC_YNR_BASE + 0x0080UL)
#define ISP_YUV_REC_YNR_L5_CFG2                 (ISP_YUV_REC_YNR_BASE + 0x0084UL)
#define ISP_YUV_REC_YNR_L5_CFG3                 (ISP_YUV_REC_YNR_BASE + 0x0088UL)
#define ISP_YUV_REC_YNR_L5_CFG4                 (ISP_YUV_REC_YNR_BASE + 0x008CUL)
#define ISP_YUV_REC_YNR_L5_CFG5                 (ISP_YUV_REC_YNR_BASE + 0x0090UL)

#define ISP_YUV_REC_UVDELAY_BASE                (0x9B00UL)
#define ISP_REC_UVDELAY_PARAM                   (ISP_YUV_REC_UVDELAY_BASE + 0x0010UL)
#define ISP_REC_UVDELAY_STEP                    (ISP_YUV_REC_UVDELAY_BASE + 0x0014UL)

#define ISP_DEWARPING_BASE                      (0xa000UL)
#define ISP_DEWARPING_PARA                      (ISP_DEWARPING_BASE + 0x0010UL)
#define ISP_DEWARPING_DST_SIZE                  (ISP_DEWARPING_BASE + 0x0014UL)
#define ISP_DEWARPING_GRID_SIZE                 (ISP_DEWARPING_BASE + 0x0018UL)
#define ISP_DEWARPING_GRID_NUM                  (ISP_DEWARPING_BASE + 0x001CUL)
#define ISP_DEWARPING_POS                       (ISP_DEWARPING_BASE + 0x0020UL)
#define ISP_DEWARPING_SRC_SIZE                  (ISP_DEWARPING_BASE + 0x0024UL)
#define ISP_DEWARPING_FSTART                    (ISP_DEWARPING_BASE + 0x0028UL)
#define ISP_DEWARPING_FDONE                     (ISP_DEWARPING_BASE + 0x002CUL)
#define ISP_DEWARPING_NFULL_SIZE                (ISP_DEWARPING_BASE + 0x0030UL)
#define ISP_DEWARPING_SLICE_START               (ISP_DEWARPING_BASE + 0x0034UL)
#define ISP_DEWARPING_MB_NUM                    (ISP_DEWARPING_BASE + 0x0038UL)
#define ISP_DEWARPING_INIT_OFFSET               (ISP_DEWARPING_BASE + 0x003CUL)
#define ISP_DEWARPING_CHK_SUM                   (ISP_DEWARPING_BASE + 0x0040UL)
#define ISP_DEWARPING_CROP_PARA                 (ISP_DEWARPING_BASE + 0x0044UL)

#define ISP_DEWARPING_GRID_X_CH0                (0x3a000UL)
#define ISP_DEWARPING_GRID_Y_CH0                (0x3b180UL)
#define ISP_DEWARPING_CORD_COEF_CH0             (0x3c300UL)
#define ISP_DEWARPING_PXL_COEF_CH0              (0x3cc00UL)
#define ISP_DEWARPING_CACHE_BASE                (0xa100UL)
#define ISP_DEWARPING_CACHE_PARA                (ISP_DEWARPING_CACHE_BASE + 0x0010UL)
#define ISP_DEWARPING_CACHE_FRAME_YADDR         (ISP_DEWARPING_CACHE_BASE + 0x0014UL)
#define ISP_DEWARPING_CACHE_FRAME_UVADDR        (ISP_DEWARPING_CACHE_BASE + 0x0018UL)
#define ISP_DEWARPING_CACHE_FRAME_WIDTH         (ISP_DEWARPING_CACHE_BASE + 0x001CUL)

#define ISP_FBD_RAW_SEL                         (0x0C10UL)
#define ISP_FBD_RAW_SLICE_SIZE                  (0x0C14UL)
#define ISP_FBD_RAW_PARAM0                      (0x0C18UL)
#define ISP_FBD_RAW_PARAM1                      (0x0C1CUL)
#define ISP_FBD_RAW_PARAM2                      (0x0C20UL)
#define ISP_FBD_RAW_PARAM3                      (0x0C24UL)
#define ISP_FBD_RAW_PARAM4                      (0x0C28UL)
#define ISP_FBD_RAW_PARAM5                      (0x0C2CUL)
#define ISP_FBD_RAW_PARAM6                      (0x0C30UL)
#define ISP_FBD_RAW_LOW_PARAM0                  (0x0C34UL)
#define ISP_FBD_RAW_LOW_PARAM1                  (0x0C38UL)
#define ISP_FBD_RAW_START                       (0x0C3CUL)
#define ISP_FBD_RAW_HBLANK                      (0x0C40UL)
#define ISP_FBD_RAW_LOW_4BIT_PARAM0             (0x0C44UL)
#define ISP_FBD_RAW_LOW_4BIT_PARAM1             (0x0C48UL)

#define ISP_YUV_AFBD_FETCH_BASE                 (0x0200UL)
#define ISP_YUV_DEC_AFBD_FETCH_BASE             (0x8100UL)

#define ISP_AFBD_FETCH_SEL                      (0x0010UL)
#define ISP_AFBD_FETCH_START                    (0x0014UL)
#define ISP_AFBD_FETCH_HBLANK_TILE_PITCH        (0x0018UL)
#define ISP_AFBD_FETCH_SLICE_SIZE               (0x001CUL)
#define ISP_AFBD_FETCH_PARAM0                   (0x0020UL)
#define ISP_AFBD_FETCH_PARAM1                   (0x0024UL)
#define ISP_AFBD_FETCH_PARAM2                   (0x0028UL)

#define ISP_ARBITER_WR_STATUS                   (0x0400UL)
#define ISP_ARBITER_RD_STATUS                   (0x0404UL)
#define ISP_ARBITER_ENDIAN_COMM                 (0x0410UL)
#define ISP_ARBITER_ENDIAN0                     (0x0414UL)
#define ISP_ARBITER_ENDIAN1                     (0x0418UL)
#define ISP_ARBITER_WR_PARAM0                   (0x041CUL)
#define ISP_ARBITER_WR_PARAM1                   (0x0420UL)
#define ISP_ARBITER_WR_PARAM2                   (0x0424UL)
#define ISP_ARBITER_WR_PARAM3                   (0x0428UL)
#define ISP_ARBITER_WR_PARAM4                   (0x042CUL)
#define ISP_ARBITER_WR_PARAM5                   (0x0430UL)
#define ISP_ARBITER_WR_PARAM6                   (0x0434UL)
#define ISP_ARBITER_WR_PARAM7                   (0x0438UL)
#define ISP_ARBITER_RD_PARAM0                   (0x043CUL)
#define ISP_ARBITER_RD_PARAM1                   (0x0440UL)
#define ISP_ARBITER_RD_PARAM2                   (0x0444UL)
#define ISP_ARBITER_RD_PARAM3                   (0x0448UL)
#define ISP_ARBITER_RD_PARAM4                   (0x044CUL)
#define ISP_ARBITER_RD_PARAM5                   (0x0450UL)
#define ISP_ARBITER_RD_PARAM6                   (0x0454UL)
#define ISP_ARBITER_RD_PARAM7                   (0x0458UL)
#define ISP_ARBITER_CHK_SUM_CLR                 (0x0460UL)
#define ISP_ARBITER_CHK_SUM0                    (0x0464UL)

#define ISP_AXI_WR_MASTER_STATUS                (0x0500UL)
#define ISP_AXI_RD_MASTER_STATUS                (0x0504UL)
#define ISP_AXI_ITI2AXIM_CTRL                   (0x0510UL)
#define ISP_AXI_ARBITER_WQOS                    (0x0514UL)
#define ISP_AXI_ARBITER_RQOS                    (0x0518UL)
#define ISP_AXI_ISOLATION                       (0x051CUL)
#define ISP_AXI_PARAM0                          (0x0520UL)
#define ISP_AXI_PARAM1                          (0x0524UL)
#define ISP_AXI_PARAM2                          (0x0528UL)
#define ISP_AXI_PARAM3                          (0x052CUL)
#define ISP_AXI_CACHE_ACTIVE                    (0x052CUL)
#define ISP_AXI_CHK_SUM_CTRL                    (0x052CUL)
#define ISP_AXI_TIMEOUT_PARAM                   (0x0558UL)
#define ISP_AXI_SECURITY_CRTL                   (0x055cUL)

#define ISP_MMU_VERSION                         (0x0000UL)
#define ISP_MMU_EN                              (0x0004UL)
#define ISP_MMU_INT_EN                          (0x00A0UL)
#define ISP_MMU_INT_CLR                         (0x00A4UL)
#define ISP_MMU_INT_STS                         (0x00A8UL)
#define ISP_MMU_INT_RAW                         (0x00ACUL)

#define ISP_BASE_ADDR(idx)                      (*(isp_cfg_poll_addr[idx]))
#define ISP_GET_REG(reg)                        (ISP_PHYS_ADDR(0) + (reg))

#define ISP_REG_WR(idx, reg, val)               (REG_WR(ISP_BASE_ADDR(idx) + (reg), (val)))
#define ISP_REG_RD(idx, reg)                    (REG_RD(ISP_BASE_ADDR(idx) + (reg)))
#define ISP_REG_MWR(idx, reg, msk, val)         (ISP_REG_WR((idx), (reg), ((val) & (msk)) |(ISP_REG_RD((idx), (reg)) & (~(msk)))))
#define ISP_REG_OWR(idx, reg, val)              (ISP_REG_WR((idx), (reg), (ISP_REG_RD((idx), (reg)) | (val))))

#define ISP_HREG_WR(reg, val)                   (REG_WR(s_isp_regbase[0] + (reg), (val)))
#define ISP_HREG_RD(reg)                        (REG_RD(s_isp_regbase[0] + (reg)))
#define ISP_HREG_MWR(reg, msk, val)             (REG_WR(s_isp_regbase[0] + (reg), ((val) & (msk)) | (REG_RD(s_isp_regbase[0] + (reg)) & (~(msk)))))
#define ISP_HREG_OWR(reg, val)                  (REG_WR(s_isp_regbase[0] + (reg), (REG_RD(s_isp_regbase[0] + (reg)) | (val))))

#define ISP_MMU_BASE s_isp_mmubase
#define ISP_MMU_WR(reg, val)                    (REG_WR(ISP_MMU_BASE+(reg), (val)))
#define ISP_MMU_RD(reg)                         (REG_RD(ISP_MMU_BASE+(reg)))
#define ISP_MMU_MWR(reg, msk, val)              ISP_MMU_WR((reg), ((val) & (msk)) | (ISP_MMU_RD(reg) & (~(msk))))

#endif
