# SPDX-License-Identifier: GPL-2.0
obj-$(CONFIG_SPRD_POWER_DOMAIN)		+= sprd_pm_domain.o
obj-$(CONFIG_SPRD_VSP_PW_DOMAIN)	+= sprd_vsp_pw_domain.o

obj-$(CONFIG_SPRD_CAMSYS_PW_DOMAIN)	+= sprd_camsys_pw_domain.o
sprd_camsys_pw_domain-objs := sprd_camsys_pw_domain_drv.o sprd_camsys_pw_domain_r4p0.o sprd_camsys_pw_domain_r5p0.o \
				sprd_camsys_pw_domain_r5p1.o sprd_camsys_pw_domain_r7p0.o sprd_camsys_pw_domain_r8p0.o

obj-$(CONFIG_SPRD_DISP_PM_DOMAIN_SHARKL3)	+= sprd_disp_pm_domain_sharkl3.o
