# SPDX-License-Identifier: GPL-2.0
obj-$(CONFIG_SPRD_POWER_DOMAIN)		+= sprd_pm_domain.o
obj-$(CONFIG_SPRD_VSP_PW_DOMAIN)	+= sprd_vsp_pw_domain.o
obj-$(CONFIG_SPRD_CAMSYS_PW_DOMAIN)	+= sprd_camsys_pw_domain.o
