# SPDX-License-Identifier: GPL-2.0
obj-$(CONFIG_SPRD_POWER_DOMAIN)		+= sprd_pm_domain.o
obj-$(CONFIG_SPRD_VSP_PW_DOMAIN)	+= sprd_vsp_pw_domain.o
obj-$(CONFIG_SPRD_VPU_PW_DOMAIN)	+= sprd_vpu_pw_domain.o

obj-$(CONFIG_SPRD_DISP_PM_DOMAIN_SHARKL3)	+= sprd_disp_pm_domain_sharkl3.o
