obj-$(CONFIG_SPRD_POWER_STAT_CORE)  += sprd-debugstat-core.o
obj-$(CONFIG_SPRD_POWER_STAT_SHARKL6) += sprd-debugstat-sharkl6.o
obj-$(CONFIG_SPRD_POWER_STAT_SHARKL5PRO) += sprd-debugstat-sharkl5pro.o

