# SPDX-License-Identifier: GPL-2.0
#
# Makefile for the Linux network device drivers.
#

#
# Networking Core Drivers
#
obj-$(CONFIG_UNISOC_SIPC_SETH)		+= seth/

#
# Sipa sys Drivers
#
obj-$(CONFIG_UNISOC_SIPA_SYS) += sipa_sys/

#
# Sipa core Drivers
#
obj-$(CONFIG_UNISOC_SIPA_V3) += sipa_v3/

#
# Sipa delegate Drivers
#
obj-$(CONFIG_UNISOC_SIPA_DELEGATE) += sipa_delegate/

#
# URSP report module
#
obj-$(CONFIG_UNISOC_URSP_REPORT) += ursp/
