sysdump-$(CONFIG_SPRD_SYSDUMP) += \
		unisoc_sysdump.o \
		unisoc_vmcoreinfo.o

obj-$(CONFIG_SPRD_SYSDUMP) += sysdump.o

obj-$(CONFIG_SPRD_NATIVE_HANG_MONITOR) += native_hang_monitor.o
obj-$(CONFIG_UNISOC_LASTKMSG)	+= unisoc_dump_info.o
obj-$(CONFIG_UNISOC_DUMP_IO)   += unisoc_dump_io.o
