#obj-y := gt9xx.o gt9xx_update.o goodix_tool.o
obj-$(CONFIG_TOUCHSCREEN_GT9XX_TS)		+= gt9xx.o
obj-$(CONFIG_TOUCHSCREEN_GT9XX_UPDATE)	+= gt9xx_update.o
obj-$(CONFIG_TOUCHSCREEN_GT9XX_TOOL)	+= goodix_tool.o
