obj-$(CONFIG_PINCTRL_SPRD)		+= pinctrl-sprd.o
obj-$(CONFIG_PINCTRL_SPRD_SC9860)	+= pinctrl-sprd-sc9860.o
obj-$(CONFIG_PINCTRL_SPRD_SHARKL5)      += pinctrl-sprd-sharkl5.o
obj-$(CONFIG_PINCTRL_SPRD_ROC1)		+= pinctrl-sprd-roc1.o
