# SPDX-License-Identifier: GPL-2.0-only
obj-$(CONFIG_PINCTRL_SPRD)		+= pinctrl-sprd.o
obj-$(CONFIG_PINCTRL_SPRD_SC9860)	+= pinctrl-sprd-sc9860.o
obj-$(CONFIG_PINCTRL_SPRD_SHARKL5PRO)	+= pinctrl-sprd-sharkl5Pro.o
obj-$(CONFIG_PINCTRL_SPRD_QOGIRL6PRO)	+= pinctrl-sprd-qogirn6pro.o
