
obj-$(CONFIG_SPRD_CAMERA_CSI_R1P0) += csi_sprd/r1p0/
obj-$(CONFIG_SPRD_CAMERA_CSI_R2P0) += csi_sprd/r2p0/
obj-$(CONFIG_SPRD_CAMERA_CSI_R2P0V2) += csi_sprd/r2p0v2/
obj-$(CONFIG_SPRD_CAMERA_CSI_RECEIVER_R1P0) += csi_sprd/receiver_r1p0/
obj-$(CONFIG_SPRD_CAMERA_CSI_RECEIVER_R2P0) += csi_sprd/receiver_r2p0/
obj-$(CONFIG_SPRD_CAMERA_CSI_RECEIVER_R2P1) += csi_sprd/receiver_r2p1/
obj-$(CONFIG_SPRD_CAMERA_CSI_11A) += csi_intel/11a/
obj-$(CONFIG_SPRD_CAMERA_CSI_DWC_11A) += csi_intel/dwc_host1.11a/
