#SPRD CODEC SMART PA

SPRD_SOUND_TREE := drivers/unisoc_platform/audio/sprd
ccflags-y += -I$(srctree)/$(SPRD_SOUND_TREE)/codec/sprd

snd-soc-sprd-pa-ucp1301-objs   := ucp1301.o
obj-$(CONFIG_SND_SOC_UNISOC_PA_UCP1301) += snd-soc-sprd-pa-ucp1301.o
