
obj-$(CONFIG_SPRD_CAMERA) += isp/
obj-$(CONFIG_SPRD_CAMERA) += sensor/
obj-$(CONFIG_SPRD_CAMERA) += dcam/
obj-$(CONFIG_SPRD_CAMERA) += cpp/
obj-$(CONFIG_SPRD_CAMERA) += flash/
obj-$(CONFIG_SPRD_CAMERA) += common/
obj-$(CONFIG_SPRD_CAMERA) += cam_sl5_roc1/
obj-$(CONFIG_SPRD_CAMERA_DCAM_IF_R5P0_ISP_R6P12) += dcam_if_r5p0_isp_r6p12/

