
sprd_flash-objs := flash_drv.o flash_gpio.o front_flash_gpio.o
obj-y += sprd_flash.o
obj-$(CONFIG_PMIC_SC2731) += sc2731s/
obj-y += flash_ic_ocp8137_drv.o
obj-y += flash_sgm37891_drv.o
obj-y += flash_ic_aw3648_drv.o
obj-$(CONFIG_MFD_SC2705) += sc2705s/
obj-$(CONFIG_FLASH_SC2721) += sc2721s/
obj-$(CONFIG_PMIC_SC2720) += sc2720s/
obj-y += flash_wd3124da_drv.o
obj-$(CONFIG_FLASH_SC2703) += sc2703s/
obj-$(CONFIG_ADF) += lcd_flash/
